### ISSUE TITLE
Installation fails with Venus os 3.00~15

### ISSUE THREAD

**Issue by testpaul999** [kwindrem/GuiMods#100]
Installation fails after update to Venus os 3.00~15
![021C7F53-B3D9-4C49-BD51-5836C604D4AE](https://user-images.githubusercontent.com/35597907/212684655-ae179d11-035e-43ca-a71e-d06ca80f6623.jpeg)

**Comment by kwindrem** [comment]
v7.10 supports v3.00~15

**Comment by testpaul999** [comment]
Thx run fine 👍🏻
