### ISSUE TITLE
VRM shows none exciting device

### ISSUE THREAD

**Issue by Next9999** [kwindrem/GuiMods#101]
VRM Portal shows none exciting device after a crash.... i had an issue with my micro SD ... on my RASP 3B

i re-did an installation but the VRM Portal show some device that i don't have

How to remove this?

![image](https://user-images.githubusercontent.com/54117519/212936705-42bdd142-1de7-4271-b8a7-de5fbf66e79e.png)

**Comment by kwindrem** [comment]
VRM is not influenced in any way by GuiMods.

Please post this question to the Victron Community Forum for help.
