### ISSUE TITLE
current limit always set back to initial value

### ISSUE THREAD

**Issue by teefixx** [kwindrem/GuiMods#109]
Hi
When I set "current limit" to eg 10A everything looks fine until I press "Accept New". It then switches to the start page and when I go back into the sub screen "AC Input Detail" nothing changed. It's always back to the original value.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/35899354/216755085-1a64614e-cbb3-4e55-a0ea-509995c810b2.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/35899354/216755127-056d3b26-2195-4f30-8975-f93c027b5a6f.png">

**Comment by kwindrem** [comment]
The Multi/Quattro must be programmed to allow input current limit changes. In addition a digital multi control or certain BMS will prevent current limit changes. I am not checking for these. The stock Victron Mobile Overview does check these items. I guess I should add these.

It also appears I have a bug in displaying the graph in the detail page.

**Comment by teefixx** [comment]
Hi
Thank you for your reply. I know thought I know the Multis quite well, but never knew that they can be programmed to allow input current limit changes... 
Can you give me a hint please?
thank you

**Comment by kwindrem** [comment]
It is in the General configuration and the parameter is "Overruled by remote". This needs to be on in order to allow input current limit changes from the GX device or Digital Multi Control.

**Comment by kwindrem** [comment]
I've changed the AC details page to show "current limit is not adjustable". The buttons to make changes are also hidden.
