### ISSUE TITLE
Threshold W/kW works on my PV charger, but not the inverter

### ISSUE THREAD

**Issue by teefixx** [kwindrem/GuiMods#115]
Hi
In my installation the threshold for W/kW os inly recognized for the PV charger, but not for the PV inverter.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/35899354/217245133-f46bcc39-5382-45a9-8440-63a47de5992c.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/35899354/217245029-470957e7-4134-4d9e-9afe-052dc45fca12.png">

**Comment by kwindrem** [comment]
I have identified the problem and this will be fixed in the next release.. Thanks for calling this to my attention.
