### ISSUE TITLE
Temperature Scale missing

### ISSUE THREAD

**Issue by houlster** [kwindrem/GuiMods#118]
Just installed v7.15.  In the setup for it, "Temperature Scale" is missing.  Do I have to install and older version to get this?

**Comment by kwindrem** [comment]
Victron added a system wide temperature scale a few versions back. If that exists, I hide the custom one in GuiMods preferences. Use the system wide one: Settings / Display & language / Units

**Comment by houlster** [comment]
Found it!  Thx.
