### ISSUE TITLE
Cannot install on Venus OS v2.93

### ISSUE THREAD

**Issue by morphias2004** [kwindrem/GuiMods#120]
Package Manager says it's incompatible with V2.93, so doesn't give the Install option.

**Comment by kwindrem** [comment]
GuiMods v7.16 installs fine here on Venus OS v2.93. v2.93 support was added to GuiMods as of v7.14.

Try downloading GuiMods again and see if that clears the incompatibility.

Next step would be to switch to the previous firmware in the Stored backup area then do a fresh online update to v2.93.

**Comment by morphias2004** [comment]
> GuiMods v7.16 installs fine here on Venus OS v2.93. v2.93 support was added to GuiMods as of v7.14.
> 
> Try downloading GuiMods again and see if that clears the incompatibility.
> 
> Next step would be to switch to the previous firmware in the Stored backup area then do a fresh online update to v2.93.

Issue is now resolved.

For clarification, this occurred on a Victron Cerbo GX following an update from v2.92 to v2.93.

Following a reboot of the Cerbo GX, doing a download again in Package Manager and then rebooting again, GUIMods was automatically reinstalled after the reboot.
