### ISSUE TITLE
Screen Rotation Option :-)

### ISSUE THREAD

**Issue by Next9999** [kwindrem/GuiMods#121]
Hello

Could you add Screen Rotation Option ... raspberry screen 7 inch

Tks

**Comment by kwindrem** [comment]
RpiDisplaySetup provides a rotation option. It is beyond the scope of GuiMods to include screen rotation for all platforms and I wouldn't even know how to do this for Cerbo or other Victron platforms since they don't use the same boot mechanism as Raspberry PI.
