### ISSUE TITLE
How do to show smartshunt auxiliary input on flow?

### ISSUE THREAD

**Issue by ijpitts** [kwindrem/GuiMods#124]
I would like to have the auxiliary input of my smartshunt connected to my start battery shown on one of the flows. Is this currently possible? 
<img width="395" alt="Screenshot 2023-02-24 at 10 51 32 AM" src="https://user-images.githubusercontent.com/126271722/221224953-f2519cd7-c465-4bc4-915f-92cd281f9562.png">
<img width="395" alt="Screenshot 2023-02-24 at 10 50 43 AM" src="https://user-images.githubusercontent.com/126271722/221225076-9dc6bbd3-b0c6-478c-9150-4e1897dae7a2.png">
<img width="486" alt="Screenshot 2023-02-24 at 10 56 53 AM" src="https://user-images.githubusercontent.com/126271722/221225461-04bc05ce-00ad-4bfb-8fb3-fb2d37396b48.png">

**Comment by kwindrem** [comment]
While it appears that space is available in the battery tile, it is in fact full, so no space to display the aux battery voltage of the shunt.

**Comment by ijpitts** [comment]
Any chance we could get a page that just shows all the batteries? I will eventually have house batteries, thruster batteries, generator starting battery, port engine starting batteries, and starboard engine starting batteries. Ian Pitts602-312-4773On Feb 24, 2023, at 1:21 PM, kwindrem ***@***.***> wrote:﻿
While it appears that space is available in the battery tile, it is in fact full, so no space to display the aux battery voltage of the shunt.

**Comment by kwindrem** [comment]
Are you suggesting a new page you get to by swiping on the current page?

**Comment by ijpitts** [comment]
Yes, one dedicated to only battery levels Ian Pitts602-312-4773On Feb 26, 2023, at 12:17 PM, kwindrem ***@***.***> wrote:﻿
Are you suggesting a new page you get to by swiping on the current page?
