### ISSUE TITLE
Wrong flow direction in AC coupled display

### ISSUE THREAD

**Issue by chaerle** [kwindrem/GuiMods#125]
On the attached picture, the  flow direction is wrong. The display shows current flowing out if "AC  in loads" instead of into.  The victron standard  display is correct.
Also the flow between pv on input to loads is the wrong direction.
![grafik](https://user-images.githubusercontent.com/28898036/221368195-0caa401c-3627-4ba3-97a1-7cdbfb9a6a81.png)

**Comment by kwindrem** [comment]
Just so I make the correct changes, please verify:

The segment from the inverter AC input to the "input bus" is based on a parameter from the inverter itself so I'm guessing this one is correct.

Then I believe the segment between the inverter input line to the PV on Input line is backwards based on your drawing.

The segment from the AC In Loads to the PV on Input line is also backwards.

All correct?

**Comment by chaerle** [comment]
Yes

**Comment by chaerle** [comment]
Also there is no PV on output. Can this be hidden?

**Comment by kwindrem** [comment]
Thanks for the confirmation. I found the issue with PV on Output and will fix that also.

**Comment by kwindrem** [comment]
I have a beta version that includes a fix for the Loads on Output flow direction and correctly hiding the PV on Output

In PackageManager / Active packages / GitHub branch or tag, change to "beta" to download/install this version.

Please have a look and make sure It's working correctly.

You can stay on the beta branch to continue to receive updates but as soon as the beta test is over, you need to switch back to "latest" to get future updates.

**Comment by chaerle** [comment]
Problem fixed.
