### ISSUE TITLE
Temperature Daily High/Low

### ISSUE THREAD

**Issue by Elmoship** [kwindrem/GuiMods#126]
Hello.  I am a new user to GuiMods and I appreciate the hard work that led to the additional capabilities and ease of use.  
I just installed several Ruuvitag temperature sensors and am wondering if a daily high/low temperature is available or could be added?

**Comment by kwindrem** [comment]
I can't do anything in GuiMods. This would require constant monitoring of the temp sensor and recording max/min values.

**Comment by Elmoship** [comment]
Thanks.

Byron Flynn
208-724-8530
________________________________
