### ISSUE TITLE
PV Inverter flow points missing in Simple View

### ISSUE THREAD

**Issue by chaerle** [kwindrem/GuiMods#127]
1) The flow points are missing in  simple  view.
2) Also connection  is wrong. PV inverter is connected to AC  in not AC out so current is not flowing through the multi as displayed.
![grafik](https://user-images.githubusercontent.com/28898036/222122965-f0efc3c5-b3b1-4130-9520-863bff7b5c9b.png)

**Comment by kwindrem** [comment]
The lack of flow bubbles on the PV Inverter tile is actually a bug in the stock Victron code. But I'll fix it.

This page combines PV on AC input and AC output. To properly show the connection, separate connections would be needed from this tile to the AC input bus and AC output bus. Or better yet, have separate tiles. The connection to the multi is incorrect even for PV on AC output. I'm afraid there's nothing I can do to improve the situation. The AC coupled flow page better shows the actual connections.
