### ISSUE TITLE
Time in overview not centered

### ISSUE THREAD

**Issue by The2Earthlings** [kwindrem/GuiMods#128]
I have a clean install with lautest Venus OS with guimods 7.16 on my rpi and the overview shows the time not centered. (Remote and on my touchscreen)
Can you pls change this?

thx Norbert 
![664A3E5B-51CE-492B-AA28-D7A420B5376D](https://user-images.githubusercontent.com/100387182/222928511-036a3bdd-0b07-4499-a94a-c217f822b072.jpeg)

**Comment by kwindrem** [comment]
The time is off center to allow space the DC connection from the Multi.
![Screen Shot Flow Overview DC Coupled](https://user-images.githubusercontent.com/58538395/222930208-9fb6eea2-015a-46b5-98c2-3b5395eb393e.png)

**Comment by The2Earthlings** [comment]
@kwindrem but if no connection available to a Multi in System (e.g. No Multi in System) it should be centered.

**Comment by kwindrem** [comment]
In reality, the Multi tile should not be shown at all since there really isn't one.

**Comment by The2Earthlings** [comment]
So the displayed multi is a bug? Does it make sense then to remove it the multi in guimods view? (And display only the time)?

**Comment by kwindrem** [comment]
Technically, components that do not exist don't appear on the flow page. Victorn's stock flow page always shows the inverter and battery even if they do not exist. I didn't change that. The stock flow also shows the inverter connections so the DC one would always be present. If no components exist, this would create a blank page which isn't a good thing as it looks like a GUI crash.

With such a minimal system, you might look at the GuiMods Simple flow page.

I'll look to see what changes make sense.

**Comment by The2Earthlings** [comment]
Thx a lot. Will you still display the time if the invertier tile is hidden? Maybe a bit bigger and centered and a bit more on top.

**Comment by kwindrem** [comment]
I'm not hiding the inverter tile

**Comment by The2Earthlings** [comment]
Oh yes sorry.
