### ISSUE TITLE
NMEA2000 temps to temps section of GUI, possible?

### ISSUE THREAD

**Issue by virtuvas** [kwindrem/GuiMods#13]
hi there,

got all the tools running fine, v.well done and many thanks!
I see now in the gui that I can have tanks and temps. Problem is that on my boat black/diesel/freshwater tank levels as well as 2X fridge, cabin, outside, water temps are produced from N2K devices and flow in the bus. 
What would be the process to get them back to the raspberry and present them on the venusOS dash?
Would make life much easier as one touch and you get both electrical vital statistics as well as tanks and temps! Saves you looking at other displays around the boat...

rpi3B+ running 2.80 large with signalk and n2k comms already configured and sending to an offsite influxDB.

in issue $6 you mention: "Any temperature sensor that appears as a dBus services should appear"
how can it be done with N2K sourced data?

cheers

V.

**Comment by virtuvas** [comment]
good morning, following a discussion with mvader on venus Modifications, I'm back in trying to see why the following two services are not installed. I'd rather go step by step, and not mess about with too many things. Never pans out right...
So I'm missing:

```
vecan-dbus.can0
mqtt-n2k.can0
```
Just re run your VeCanSetup script, same thing can-bus-bms installed, the other two not.

Looking at your script I see at line19:
services="can-bus-bms vecan-dbus mqtt-n2k"

and at the end line 564 a for loop that from my little scripting/programming knowledge would expect it loops through the three entries in services above and runs the installation on all of them.
Am I missing something earlier in the script that would make it do just the first installation? Tempted to remove the first record out of services on line 19 and run it again to see if it installs vecan-dbus :-)
TBH, manually installing the services doesn't seem to appealing as the Feb wiki seems not to match the way the other services are installed now.

for the record this is my /services dir listing:

```
root@raspberrypi2:/service# ls -la
drwxr-xr-x    1 root     root           860 Aug 27 16:37 .
drwxr-xr-x   21 root     root          4096 Aug 25 10:59 ..
drwxr-xr-x    1 root     root            60 Aug 27 16:37 SetupHelper
drwxr-xr-x    1 root     root            80 Aug 27 16:37 can-bus-bms.can0
drwxr-xr-x    1 root     root            80 Aug 27 16:37 can-bus-bms.can1
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-adc
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-digitalinputs
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-fronius
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-generator-starter
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-modbus-client
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-modbustcp
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-motordrive.can0
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-motordrive.can1
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-mqtt
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-pump
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-qwacs
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-systemcalc-py
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-valence.can0
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-valence.can1
drwxr-xr-x    1 root     root            80 Aug 27 16:37 dbus-vebus-to-pvinverter
drwxr-xr-x    1 root     root            80 Aug 27 16:37 gui
drwxr-xr-x    1 root     root            80 Aug 27 16:37 hub4control
drwxr-xr-x    1 root     root            80 Aug 27 16:37 llmnrd
drwxr-xr-x    1 root     root            80 Aug 27 16:37 localsettings
drwxr-xr-x    1 root     root            80 Aug 27 16:37 mosquitto
drwxr-xr-x    1 root     root            80 Aug 27 16:37 mqtt-rpc
drwxr-xr-x    1 root     root            80 Aug 27 16:37 netmon
drwxr-xr-x    1 root     root            80 Aug 27 16:37 node-red
drwxr-xr-x    1 root     root            80 Aug 27 16:37 openssh
drwxr-xr-x    1 root     root            80 Aug 27 16:37 ppp
drwxr-xr-x    1 root     root            80 Aug 27 16:37 serial-starter
drwxr-xr-x    1 root     root            80 Aug 27 16:37 service-advertiser
drwxr-xr-x    1 root     root            80 Aug 27 16:37 signalk-server
drwxr-xr-x    1 root     root            80 Aug 27 16:37 simple-upnpd
drwxr-xr-x    1 root     root            80 Aug 27 16:37 socketcand
drwxr-xr-x    1 root     root            80 Aug 27 16:37 ssh-tunnel
lrwxrwxrwx    1 root     root            49 Aug 27 16:37 vedirect-interface.ttyUSB0 -> /var/volatile/services/vedirect-interface.ttyUSB0
lrwxrwxrwx    1 root     root            49 Aug 27 16:37 vedirect-interface.ttyUSB1 -> /var/volatile/services/vedirect-interface.ttyUSB1
drwxr-xr-x    1 root     root            80 Aug 10 14:06 vegetty
drwxr-xr-x    1 root     root            80 Aug 27 16:37 venus-html5-logger
drwxr-xr-x    1 root     root            80 Aug 27 16:37 vesmart-server
drwxr-xr-x    1 root     root            80 Aug 27 16:37 vrmlogger
drwxr-xr-x    1 root     root            80 Aug 27 16:37 websockify-c
```
clearly missing the two mentioned at the beginning. 
any suggestions welcomed!

cheers
V.

**Comment by virtuvas** [comment]
> Am I missing something earlier in the script that would make it do just the first installation? Tempted to remove the first record out of services on line 19 and run it again to see if it installs vecan-dbus :-)
> TBH, manually installing the services doesn't seem to appealing as the Feb wiki seems not to match the way the other services are installed now.

re-run the script, having edited line 19 as : services="vecan-dbus mqtt-n2k"

same result, just edits config.txt note the log below it mentions only three services installed:

```
root@raspberrypi2:/data/VeCanSetup# ./setup

Raspberry PI - no built-in CAN ports
VeCan configurations
can0 Waveshare Hat 8 MHz crystal
can1 no configuration

Available actions:
  Add interface configurations (a)
  Modify interface configurations (m)
  Remove interface configurations (x)

  Install and activate interfaces (i)
  Reinstall (r) based on options provided at last install
  Uninstall (u) and restore all files to stock

  Display interface information (d)
  Display setup log (l) outputs the last 100 lines of the log
  Quit (q) without further action

Choose an action from the list above: r
installing package
adding overlay for can0 to config.txt

revised information
can0 Waveshare Hat 8 MHz crystal
can1 no configuration

information for can0
  udev info  vendor=  model Id=  vendor id=  serial=
  overlay: dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000
dtoverlay=mcp2515-can0,oscillator=8000000,interrupt=25,spimaxfrequency=1000000
  services: can-bus-bms.can0 dbus-motordrive.can0 dbus-valence.can0
information for can1
  no udev information available
  overlay: none
  services: can-bus-bms.can1 dbus-motordrive.can1 dbus-valence.can1

new interfaces will not become active until after a reboot
Reboot system now (y) or issue a reboot manually later (n): n
system must be rebooted to finish installation and activate components
```
any ideas why only the above services are installed?

V.

**Comment by kwindrem** [comment]
It's a bug in v2.80. All services are pre-installed in v2.80 but the mqtt-dbus and vecan-dbus services are not included in the RPI 4 build.

Here is a set of tar files you can extract in /opt/victronenergy/service:

[mqtt-n2k.can0.tar.zip](https://github.com/kwindrem/GuiMods/files/7070388/mqtt-n2k.can0.tar.zip)
[mqtt-n2k.can1.tar.zip](https://github.com/kwindrem/GuiMods/files/7070389/mqtt-n2k.can1.tar.zip)
[vecan-dbus.can0.tar.zip](https://github.com/kwindrem/GuiMods/files/7070390/vecan-dbus.can0.tar.zip)
[vecan-dbus.can1.tar.zip](https://github.com/kwindrem/GuiMods/files/7070391/vecan-dbus.can1.tar.zip)

**Comment by virtuvas** [comment]
interesting!
i'm rpi3B+ guess it makes no difference right?

V.

**Comment by virtuvas** [comment]
OK, did it, complained about magic number, finally unzipped and untarred it in windows and xfered it over.
Re run your script, now reports that:

```
information for can0
  udev info  vendor=  model Id=  vendor id=  serial=
  overlay: dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000
dtoverlay=mcp2515-can0,oscillator=8000000,interrupt=25,spimaxfrequency=1000000
  services: can-bus-bms.can0 dbus-motordrive.can0 dbus-valence.can0 mqtt-n2k.can0 vecan-dbus.can0
```

so in theory mqtt-n2k and vecan-dbus should be ok on can0. now processes running are similar to yours except that I don't have 
supervise socketcand
and
29085 root 3608 S /opt/victronenergy/vecan-dbus/vecan-dbus -c socketcan:can0 --banner --log-before 25 --log-a
the latter implies that vecan-dbus is not running. Have to look into that.

Most important issue is that access denied below:
```
root@raspberrypi2:/data/VeCanSetup# ps | grep can
  825 root      9076 S    /usr/sbin/wpa_supplicant -u -O /var/run/wpa_supplicant -s
  939 root      2956 S    {svscanboot} /bin/sh /usr/bin/svscanboot
  950 root      1776 S    svscan /service
  951 root      1600 S    readproctitle service errors: ...run: access denied supervise: fatal: unable to start log/run: access denied supervise: fatal: unable to start vecan-dbu
  963 root      1612 S    supervise dbus-motordrive.can0
  968 root      1612 S    supervise vecan-dbus.can0
  981 root      1612 S    supervise dbus-motordrive.can1
 1013 root      1612 S    supervise can-bus-bms.can1
 1022 root      1612 S    supervise dbus-valence.can0
 1030 root      1612 S    supervise dbus-valence.can1
 1034 root      1612 S    supervise can-bus-bms.can0
 1036 root      1612 S    supervise socketcand
 1044 root      1612 S    supervise mqtt-n2k.can0
 1533 root      3164 S    /opt/victronenergy/can-bus-bms/can-bus-bms --log-before 25 --log-after 25 -vv -c socketcan:can0 --banner
 1534 root      1624 S    multilog t s25000 n4 /var/log/can-bus-bms.can0
14930 root      2692 S    grep can
```

needless to say that dbus-spy doesn't show com.victronenergy.vecan.can0

Could I ask a favour to convert the four files in tar.gz from tar.zip, seems that rpi is not happy unziping them. Windows will do but not sure if something is wrong in the whole process.

cheers

V.

**Comment by kwindrem** [comment]
Not sure why you are seeing what you are but I went ahead and updated the setup script for VeCanSetup to install the missing services.

You should remove the service directories that are somehow messed up by my previous files:
rm -r /opt/victronenergy/service/vecan-dbus.can0
rm -r /opt/victronenergy/service/vecan-dbus.can1
rm -r /opt/victronenergy/service/mqtt-n2k.can0
rm -r /opt/victronenergy/service/mqtt-n2k.can1

then reboot

If you have automatic updates turned on, you'll get the fix automagically. If not, you can fetch a new version from here, then run the setup script again.

**Comment by virtuvas** [comment]
thanks!

did that, reinstalled (as in running /data/VeCanSetup/setup and selecting "r" as the option)
now works without any errors on ps | grep can which is good.

Interestingly, still get this on ps:

```
root@raspberrypi2:/data/VeCanSetup# ps | grep can
  825 root      9204 S    /usr/sbin/wpa_supplicant -u -O /var/run/wpa_supplicant -s
  925 root      2956 S    {svscanboot} /bin/sh /usr/bin/svscanboot
  938 root      1776 S    svscan /service
  950 root      1612 S    supervise dbus-motordrive.can0
  956 root      1612 S    supervise vecan-dbus.can0
  977 root      1612 S    supervise dbus-motordrive.can1
 1006 root      1612 S    supervise can-bus-bms.can1
 1014 root      1612 S    supervise dbus-valence.can0
 1022 root      1612 S    supervise dbus-valence.can1
 1026 root      1612 S    supervise can-bus-bms.can0
 1028 root      1612 S    supervise socketcand
 1035 root      1612 S    supervise mqtt-n2k.can0
 1504 root      1756 S    multilog t s25000 n4 /var/log/vecan-dbus.can1
 1507 root      3164 S    /opt/victronenergy/can-bus-bms/can-bus-bms --log-before 25 --log-after 25 -vv -c socketcan:can0 --banner
 1508 root      1624 S    multilog t s25000 n4 /var/log/can-bus-bms.can0
14313 root         0 Z    [vecan-dbus]
14315 root      2692 S    grep can
```

no /opt/victronenergy/vecan-dbus..... Iine like I get if I manually run the command:
```
root@raspberrypi2:/data/VeCanSetup# /opt/victronenergy/vecan-dbus/vecan-dbus -c socketcan:can0 --banner --log-before 25 --log-after 25 -vv
```
Need that command to get a populated list in Settings/Services/CAN-bus(1)/Devices

I guess that's a matter of somehow deciding it's not needed to run, so I have to force that.
But as mvader points in the Modifications discussion that you also contributed yesterday (thanks!) the problem is that for some reason the data from my N2K bus are not compatible.

Off for three days, will come back on Wed trying to find what makes some data compatible. As I said, if your data come from N2K bus, would love to know where/how they are produced and if any particular settings are used in either signalk (do you use it?) or elsewhere. Temp related PGNs are a few!

cheers

V.

**Comment by kwindrem** [comment]
I did a little testing here on my RPI 4. The line that includes [vecan-dbus] indicates that the process died. I saw this same issue on my system when the CANable USB interface was not plugged in. After it was plugged in, ps showed the complete process info:

 1843 root      3620 S    /opt/victronenergy/vecan-dbus/vecan-dbus -c socketcan:can0 --banner --log-before 25 --log-after 25 -vv

All services include a log file and that shows the error:

root@raspberrypi4:~# tail -40 /var/log/vecan-dbus.can0/current|tai64nlocal
2021-08-28 09:38:03.738516500 *** starting vecan-dbus ***
2021-08-28 09:38:03.745523500 vecan-dbus 2.69
2021-08-28 09:38:03.746187500 
2021-08-28 09:38:03.746190500 -------- dumping backlog -------
2021-08-28 09:38:03.746193500 000.000 INF.canhw_drv: adding driver socketcan
2021-08-28 09:38:03.746195500 000.000 ERR.canhw_drv: Could not find gateway 'socketcan:can0'
2021-08-28 09:38:03.746259500 Specified CAN-bus gateway 'socketcan:can0' not found!
2021-08-28 09:38:03.746264500 The following gateways were found:
2021-08-28 09:38:03.746269500 --------------------------------------------------------------
2021-08-28 09:38:03.746274500 --------------------------------------------------------------
2021-08-28 09:38:03.746279500 000.000 INF.task: done in 000.000
2021-08-28 09:38:04.758692500 *** starting vecan-dbus ***
2021-08-28 09:38:04.764649500 vecan-dbus 2.69
2021-08-28 09:38:05.783935500 *** starting vecan-dbus ***
2021-08-28 09:38:05.791377500 vecan-dbus 2.69

The log excerpt shows that  the interface can't be found, which is CORRECT since the interface was not plugged in at the time. I then plugged in the interface and as the log shows, there were no errors and the process stayed running.

So we need to shift focus to your Waveshare interface, since it is likely it isn't being recognized.

My VeCanSetup package used the information in the Wiki to set up several interfaces, including the Waveshare, but I did not have the hardware to test all interfaces. I thought I had created templates for the two versions the Wiki called out but the one for the 12 MHz crystal is missing. Could this be your issue?

Try updating VeCanSetup and running the setup script, modifying the can0 interface to Waveshare Hat 12 MHz crystal.

If not, and since you did the initial work on the Waveshare interface, maybe you can dig into that and check my work.

**Comment by virtuvas** [comment]
Kevin, moving here from  community victron as this is specific to our discussion here (I think!)

now, you sent me vecan-dbus.can0 and installed it. However, when I go to 
/service/vecan-dbus.can0/
run mentions socketcan:can1
same goes for /log/run
If I edit them and then reboot the system, they are back to can1

could it be some issue with the can0 and can1 tar.gz you gave me. 
seems that code in /opt/victronenergy/system/vecan-dbus.can0 is also wrong (pointing to can1)
edited all that to point to .can0, system boots, SOME devices are shown on the bus, not all and not tanks.
Further /data/log/vecan-dbus/ points to version 2.56 whereas if I run my command:
`/opt/victronenergy/vecan-dbus/vecan-dbus -c socketcan:can0 --banner --log-before 25 --log-after 25 -vv &`
it comes back with 2.69.
I'm obvs missing a few things but my head is about to break so cannot go any further atm.

cheers

V.

**Comment by virtuvas** [comment]
well restored config.txt to the one for waveshare on the wiki, edited /opt/victronenerge/system/vecan-dbus.can0 to point to can0, rebooted all is working fine.
So just check please if your can0 dir is really pointing to can0 in the run files (or I got something messed up myself.

cheers

V.

**Comment by kwindrem** [comment]
VeCanSetup will

**Comment by kwindrem** [comment]
I didn't find any bugs creating services with the wrong pointers.

In v2.80, /service is an overlay from /opt/v*/service, so any changes need to be made there if they are to survive a reboot.

If the service directory exists, VeCanSetup will not change it even if it is not correct.

For Raspberry PI, VeCanSetup permits changing both can0 and can 1. For Cerbo, it won't allow either to be modified since they are supported natively. Other platforms have only can0 so VeCanSetup can modify can1.

If VeCanSetup finds a port in /etc/venus/canbus_ports but has not made a configuration for it, it assumes it was created elsewhere and leaves it alone.

I did fix a bug that does not update canbus_ports when removing an interface. That might have prevented things from updating properly due to other checks.

If the services are incorrect, you should remove them manually (from /opt/v*/services), reboot then rerun /data/VeCanSetup/setup and reinstall.

**Comment by virtuvas** [comment]
thanks, this explains some oddities.

One (hopefully last) comment on the behaviour of this script for your perusal.
Every time I run one of your scripts (last night I run /data/GuiMods/setup ) it did edit (and added) an extra two lines on my /u-boot/config.txt. Thing is I had the proper line for my 12MHz waveshare:

dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000

but it ignored it and appended:

dtoverlay=mcp2515-can0,oscillator=8000000,interrupt=25,spimaxfrequency=1000000
dtparam=spi=on

as  a result the whole NMEA2K bus onboard lost the gps signal and was beeping every minute or so and the rpi 7in screen was dead. No big deal, ssh in, edited the file, all's fine.

Just wondering if your script should ask before replacing/adding dtoverlay lines on config.txt. Maybe asking too much and anyway I know what happens and what to do but for sure for me means I cannot do auto updates of your scripts. It's mainly for others that are unfamiliar and will end up with various seemingly unrelated issues.

thanks again for all your work!

V.

**Comment by kwindrem** [comment]
I did some work on the install script. It now prompts for automatic overlay installs and reports the need for manually installing overlays in the status reports. This choice is per interface (can0, can1) and persists through a Venus OS upgrade or package update. Since config.txt is not touched during a Venus OS update, this should allow you to enable SetupHelper autoupdates.

Note that there are two Waveshare CANbus interfaces: one for each crystal frequency. It appears you picked the 8 MHz crystal but have the 12 MHz crystal version. Picking the right one would allow you to used the overlay lines from this package instead of manually editing config.txt.

**Comment by virtuvas** [comment]
thanks Kevin.

so I tried to run /data/VeCanSetup/setup
Indeed I somehow had the 8MHz version, now chose option  8, answered y to do you want to install the overlay and it returned:

```
can0 configuration updated
no more configurations to be modified

Raspberry PI - no built-in CAN ports
VeCan configurations
can0 Waveshare Hat 12 MHz crystal
can1 no configuration

changes are NOT active yet
select INSTALL when all changes have been made and verified

Choose an action from the list above:
```

the info returned are absolutely fine, stating what the system is about to do. No problems with that. 
However, the last line is a bit confusing to a newcomer I think as it asks you to choose an action from the list above, but if you're on an normal 80X25line terminal, you miss the list of options two pages up...
Yes, had to hit i for it to install it, but I'm worried that some ppl will miss it or get confused. Dunno, maybe re state the options? or get them with a different background or indented or something to make them stand out?

cheers

V.

**Comment by kwindrem** [comment]
Noted. I'll redisplay the options.

Other than that, is it working?

**Comment by virtuvas** [comment]
oops, sorry, of course it is!
:-)
again thanks a lot for your work, really makes rpi venus a joy to install!

V.

**Comment by seamaster101** [comment]
Did you manage to read NMEA 2000 temperature sensors on Venus RPI?

**Comment by virtuvas** [comment]
sorry, no didn't push that any further.
if you followed the discussion, it actually deviated massively from the original title as there were other issues for me to solve with Kevin's help. So best move to the new one you created.
