### ISSUE TITLE
Alternator flow dots are backwards.

### ISSUE THREAD

**Issue by iNotMario** [kwindrem/GuiMods#133]
On the main overview screen, when an alternator is outputting power, the dots flow toward it rather than away from it.

**Comment by kwindrem** [comment]
Which overview screen? GuiMods Simple, GuiMods AC Coupled, GuiMods DC Coupled.

Which version of GuiMods?

Which firmware version?

**Comment by iNotMario** [comment]
DC Coupled. v3.00~15.

**Comment by kwindrem** [comment]
OK. I'll roll the change into the next version of GuiMods

**Comment by kwindrem** [comment]
I have a beta version out it you want to test this. Change the branch/tag for GuiMods to "beta". I plan to release this to the "latest" branch after a brief test of the changes in this beta.
