### ISSUE TITLE
GuiMods wont work with V3.0~23

### ISSUE THREAD

**Issue by testpaul999** [kwindrem/GuiMods#134]
Hello,

GuiMods won’t run with the new Venus-os V3.0~23.
Regards

**Comment by EJhagenaar** [comment]
Same: 

root@beaglebone:~# /data/GuiMods/setup instal
--- starting setup script v7.17
creating file set for v3.00~23
ERROR v3.00~23 dbus_systemcalc.py no replacement file
ERROR: incomplete file set for v3.00~23 - can't continue
root@beaglebone:~#

**Comment by solarmowe** [comment]
me too

**Comment by kwindrem** [comment]
fixed in v7.18

**Comment by EJhagenaar** [comment]
It is working, Thanks!
