### ISSUE TITLE
Alternator current visually goes the wrong direction. 

### ISSUE THREAD

**Issue by svalbard2** [kwindrem/GuiMods#135]
Hi, when you moved the DC to the right something happened with the visual current from the Alternator. It goes into the Alternator.

**Comment by kwindrem** [comment]
This is on the DC or AC coupled flow page?
There are several sections of the flow line. Are they all backwards?

There have been other reports of flows backwards so I'm wondering if it depends on the source of the power number. What's shown on the Alternator details page?

What version of GuiMods are you running?
What firmware version?

**Comment by svalbard2** [comment]
![20230321_080328](https://user-images.githubusercontent.com/119114646/226609861-007678eb-27a6-467a-8d7e-df802e421436.jpg)
![20230321_080338](https://user-images.githubusercontent.com/119114646/226609913-9e593685-c148-4cb0-be91-63a4ed9b8fd7.jpg)
![20230321_080427](https://user-images.githubusercontent.com/119114646/226610007-fad574e7-5632-4f0a-8e05-5e81057c0c0e.jpg)

**Comment by svalbard2** [comment]
I cannot add a video here, but the flow from the Alternator goes into the Alternator.

**Comment by svalbard2** [comment]
![Uploading 20230321_135351.jpg…]()

**Comment by kwindrem** [comment]
Thanks for the additional info. I'll get this fixed in the next release.

**Comment by kwindrem** [comment]
I have a beta version out now that should fix the flow direction.

Switch the branch/tag for GuiMods to "beta" in Package Manager / Active Packages and you should be able to download and install the beta.

Note this beta also includes significant changes for a fix for missing voltage, current and frequency in some systems. These changes affect systemcalc so please let me know if you see any missing information on the flow pages. If you see this, send me the log for systemcalc:

tail -40 /data/log/dbus-systemcalc-py/current | tai64nlocal

Please switch the branch/tag back to "latest" when you finish testing so you get future released versions.

**Comment by svalbard2** [comment]
Hi, the flows are now correct in the beta.

Everything else look normal.


Heinrich
