### ISSUE TITLE
5th PV charger power displays incorrectly at top

### ISSUE THREAD

**Issue by svScoots** [kwindrem/GuiMods#145]
The definition for the 5th PV Charger is incorrect resulting in the watt value being at the top of the tile.

in OverviewHubEnhanced.qml  line 781
 y: pvOffset5 + pvChargerCompact ? 0 : pvRowSpacing

should be 

 y: pvOffset5 + (pvChargerCompact ? 0 : pvRowSpacing)

This fixes the problem.  I'm sorry I don't know how to fix it in github myself.

**Comment by kwindrem** [comment]
Should be fixed as ov v7.32
