### ISSUE TITLE
Temperatures from Mopeka tank sensors

### ISSUE THREAD

**Issue by helmet1978** [kwindrem/GuiMods#157]
Would it be possible to have the temperature readings from Mopeka wireless tank sensors available for display, either in the tank detail or as "regular" temperature sensors? They are available via MQTT under tank/##/Temperature

**Comment by kwindrem** [comment]
If a tank sensor shows up on dbus, I'll show it. If the Mopeka tank sensors are not showing up on dbus, then work needs to be done at a lower level to support them. This is something Victron would need to do.

**Comment by kwindrem** [comment]
According to this:

https://community.victronenergy.com/questions/148366/mopeka-pro-sensors-in-venus-29018.html

The LP and H2O sensors are already supported. They must be the Pro version though. Have you tried them?

**Comment by Eagle383** [comment]
I use the mopeka sensors. They work well you can see the temps in the sub menu and on the config page. Just not on the overlay. 
![IMG_0536](https://github.com/kwindrem/GuiMods/assets/8438904/64fc003e-baa0-4d6c-b975-7795e70de4ee)

**Comment by helmet1978** [comment]
Yes, these are all the Pro version and they look to be working fine, was just wondering about the temperatures. Thank you!
