### ISSUE TITLE
Missing PV data for Multi RS Solar?

### ISSUE THREAD

**Issue by mfu-mcosys** [kwindrem/GuiMods#159]
Maybe it is a Problem because i use a Quattro (just inverting) and a MultiRS (just charge) on the same Cerbo... 
VenusOS is 3.00
GuidMods is 7.63

![Bildschirmfoto_2023-06-14_11-02-11](https://github.com/kwindrem/GuiMods/assets/21175934/e9d11c87-8eac-46ac-bbaa-7105511bdb1e)
![Bildschirmfoto_2023-06-14_11-01-45](https://github.com/kwindrem/GuiMods/assets/21175934/9f78ca62-51b0-45c2-938c-fcc5387a89aa)

**Comment by kwindrem** [comment]
It has something to do with the Multi RS MPPT. Is this a multi-tracker device?

Do you have command line access to your Cerbo? If so, I'd like to see a screen shot of the dbus info for the RS.
If not, at least a screen shot of the device's menu.

**Comment by mfu-mcosys** [comment]
I have access through ssh on the cerbo, but which logfile is for the MultiRS?
This is the list of dbus logfiles in /var/log/

dbus-adc
dbus-ble-sensors
dbus-digitalinputs
dbus-fronius
dbus-generator-starter
dbus-modbus-client
dbus-modbustcp
dbus-mqtt
dbus-qwacs
dbus-shelly
dbus-systemcalc-py
dbus-vebus-to-pvinverter
gps-dbus.ttyUSB0
gps-dbus.ttyUSB1
gps-dbus.ttyUSB2
mk2_dbus.ttyS4
smartbms-dbus.ttyUSB0
smartbms-dbus.ttyUSB1
smartbms-dbus.ttyUSB2
vecan-dbus.can0

**Comment by kwindrem** [comment]
Not a log file but an app that shows the dbus parameters:

dbus-spy

Then select the RS and it will show you all the parameters. There may be more than fits on a screen.

I'm guessing there's something wrong with my logic that looks for multiple MPPT trackers

**Comment by mfu-mcosys** [comment]
Hope this helps a bit, maybe some info from the mqtt helps too.

![screen1](https://github.com/kwindrem/GuiMods/assets/21175934/7ee648ae-1db8-49a1-95ce-fa0b5f966708)
![screen2](https://github.com/kwindrem/GuiMods/assets/21175934/e4f8450e-3d0c-49a0-be2d-8bca8f53e0cf)

**Comment by kwindrem** [comment]
It does help. Thanks. Your RS is a single tracker so my original though was not correct.

I'm now thinking that because this a combined inverter/charger and MPPT combined, I'm not recognizing it as a PV charger. Working on changes now. Stay tuned.

**Comment by kwindrem** [comment]
I just published v7.64 as a fix for this. Please give it a try and report back.

**Comment by mfu-mcosys** [comment]
Looks nice
![Bildschirmfoto_2023-06-15_10-21-07](https://github.com/kwindrem/GuiMods/assets/21175934/66020fbe-2588-4752-ba2a-b23c060c405b)
![Bildschirmfoto_2023-06-15_10-21-21](https://github.com/kwindrem/GuiMods/assets/21175934/f8f8a7e9-7823-4435-86bc-3d4144e6284a)

Thanks a lot!

I know the AC-stuff isnt related to the "PV Charger"-Tile, but for my usage i want the combined PV/AC power for charging in the "PV Charger"-Tile. Lets see where i need to change some vars. :)

**Comment by mfu-mcosys** [comment]
seems like after the update to 10.42 today the informations on the flow are missed again :/
