### ISSUE TITLE
GuiMods and communication with v3.00

### ISSUE THREAD

**Issue by Ivo12s** [kwindrem/GuiMods#160]
Using simple configuration - external LiFePo4 battery with Victron BMV700 and standard shunt. 2x BlueSolar Charger MPPT 150/60 and Smart Phoenix Inverter 48V 5000VA 230V. GuiMods installed on Raspberry Pi4B and version 2.94. In the configuration I setting up "have DC system", where it is standard 99-118 W as continuous calculated DC load.

When I installed version 3.0, the DC Load calculated total consumption included AC load. AC Load highlighted as standard. So for simple definition presented:
Before - with v.2.94:
AC Load - 1095 W
DC Power - 118W

After - with 3.0:
AC Load - 1095 W
Solar - 1148 W
DC Power - 2275 W

The same in VRM Portal and Remote Console as well.
When downgrade into 2.94, everything goes into normal.
![VRM-test-30](https://github.com/kwindrem/GuiMods/assets/99555598/b8359ba2-6ecf-4c6b-97f4-9b4bbaba47e3)
![VRM-test-30b](https://github.com/kwindrem/GuiMods/assets/99555598/b8410207-6899-472c-bcf2-ffe0dd376525)

**Comment by kwindrem** [comment]
Does this problem still exist if you completely uninstall GuiMods?

**Comment by kwindrem** [comment]
I looked over the code and found some errors I introduced in calculating DC System power. These should be fixed in v7.65

**Comment by Ivo12s** [comment]
👍😎
