### ISSUE TITLE
User programmable display timeout

### ISSUE THREAD

**Issue by mdshw5** [kwindrem/GuiMods#161]
I've been searching for a way to control the display timeout - either with a local script or via NodeRed. What I'd like to do is keep the display on during the day (or maybe only when the PV is active), and then set a short timeout during the night. If this is already possible I'd love if if someone could point me to the resources. Otherwise it could be nice to have an option in GuiMods to toggle display timeout based on PV charger state.

**Comment by kwindrem** [comment]
The dbus parameter to control the display blanking is:

com.victronenergy.settings /Settings/Gui/DisplayOff

So it should be accessible from NodeRed.
