### ISSUE TITLE
Generator warm up/cool down timer again

### ISSUE THREAD

**Issue by thomasinaz41213** [kwindrem/GuiMods#162]
Hey Kevin a previous issue seems to have reappeared. Is some of the late v3.00 betas if you recall there were some issues with the generator warm up/cool down timers being broken when installing guimods or exttransferswitch. I am currently on Venus release v3.00 (on a cerbo gx). If I uninstall both guimods and exttransferswitch the timers work properly. Guimods installed and the timers are broken. I have tried full system reboot after installing guimods but it didn't change. Guimods is v7.65. Sorry it took me so long to test this out, life gets busy.

**Comment by kwindrem** [comment]
I found a couple of issues, one that prevented the cool-down from happening. Another issue was the running status was not always updated. I think this was only in v3.00 beta versions. v7.66 is available. These changes are also in ExtTransferSwitch v3.15.

I did not find a problem with warm-up however. 

Also found an issue in ExtTransferSwitch when reinstalling. An update to SetupHelper (now v4.42) fixed that.
