### ISSUE TITLE
File set incomplete for Venus v3.10~11

### ISSUE THREAD

**Issue by lawrencecraig1** [kwindrem/GuiMods#163]
Error displayed: GUIMods file set incomplete after updating to 3.10~11 (autoupdate)

**Comment by kwindrem** [comment]
Working on that now.

**Comment by kwindrem** [comment]
v7.67 was just released. Should work on Venus OS v3.10~11.

If anyone has a Multi 120x2 please check to see if the AC in and out details page work when the grid is in 120 volt mode and when inverting.
