### ISSUE TITLE
Background is light on web display in Dark Mode

### ISSUE THREAD

**Issue by svScoots** [kwindrem/GuiMods#164]
I am using an android phone for the display for an octoGX.  I'm loving the dark mode, (I'm on a sailboat) but the border around the active area and the background around the virtual hotkeys are both still white. Can you make the surround area dark, and dim the virtual hotkeys a bit as well? I've attached a screenshot of how it currently looks on my system.  
Venus 3.00 and GuiMods 7.68

![GuiMods_Screenshot_20230708-180953](https://github.com/kwindrem/GuiMods/assets/108607829/14d8cb8f-242e-47ea-8570-af7dc3728bfa)

**Comment by kwindrem** [comment]
This excellent work was done by @mr-manuel. I recall him saying that the areas you speak of are controlled by the device's light/dark mode, not the one selected in the GX device's menu.

It works on Safari on Mac OS, but not on my iPhone, and apparently not on your Android phone either. 

Hopefully this is something easy that he can fix.

**Comment by mr-manuel** [comment]
Hi, I‘m using an iPad and Android Tablet and it works on both, when I enable the device dark mode. I‘m using on both devices  Firefox and Brave.

**Comment by kwindrem** [comment]
Yup, seems to work on my iPad as well. So... there's something specific about the phones. This gets into the twisty maze of web site design which I'm not at all familiar with. Not sure anything can be done although I know others have posted ideas for removing the hotkeys section altogether.

**Comment by mr-manuel** [comment]
I found out, that on smaller resolutions there is another theme applied. Which phone do you have and which resolution, with which screen zoom and font size (android settings)?

**Comment by kwindrem** [comment]
I have an iPhone 13 Pro and using the default text size (whatever that is). Looks like this:

![IMG_1388](https://github.com/kwindrem/GuiMods/assets/58538395/86481648-afcd-47eb-83c7-fbc33cdabc58)

**Comment by svScoots** [comment]
I went back and tried a bunch of browsers, it works correctly in Windows 10 using Chrome in Dark mode, both the background and the hotkey background are dark and the keys are dim.  

I put Chrome in Android in dark mode and the background went dark but the hotkey background  stayed light like the above screenshot.  I put the phone in forced dark mode and there was no change.  The Brave browser on Android was the same.

**Comment by mr-manuel** [comment]
Desktop mode changes, because there are two different button sets. I will take a look at it the coming week.

**Comment by mr-manuel** [comment]
Since the hotkey background was different on devices with a width smaller than 795px it was displayed white. This will be fixed with the next version.

![Bildschirmfoto am 2023-07-10 um 08 23 48](https://github.com/kwindrem/GuiMods/assets/12592765/25291869-ad19-4464-ae34-f9e9f165dc6b)

![Bildschirmfoto am 2023-07-10 um 08 23 56](https://github.com/kwindrem/GuiMods/assets/12592765/d123477f-56cf-46fa-9f4b-8206ba20d795)

**Comment by mr-manuel** [comment]
The changes are in the main branch. The cache of the Safari browser on the mobile devices is a bit tricky. Did you try in a Private tab?

**Comment by kwindrem** [comment]
Clearing the cache worked. Thanks. I'll publish this to latest now.

**Comment by svScoots** [comment]
Great stuff! thanks everyone
