### ISSUE TITLE
Flow Chart Screen - missing status, missing LEDs

### ISSUE THREAD

**Issue by aph70** [kwindrem/GuiMods#166]
Hi all,
don't know if this issue is GuiMods related, but if not you may have the knowdlege of where do dig for the rootcause.

Past weekend I did switch from my Raspi based solution to a version with a new Cerbo GX.

For the sake of simplicity, all devices are still connected to the Cerbo via USB (VE.Direct and MK3-USB), i.e. no direct VE.Bus connection.

The problem:
The status of the Multi as well as the LEDs are no longer displayed in the flow chart screen. 
It is always "Off" or "---" even if the inverter is "On", set to "Invert only" or "Charge Only" even though it exaclty doing that.
Also the LEDs are also no longer displayed. 
It worked flowlessly  with the Raspi under the same firmwares.

![flow](https://github.com/kwindrem/GuiMods/assets/96956872/137ffa10-0869-4f44-8b9d-e4e7b6a4d85e)
![flow2](https://github.com/kwindrem/GuiMods/assets/96956872/728bd514-fc4e-4e62-a6c0-f56305330ffd)
![not-adjustable](https://github.com/kwindrem/GuiMods/assets/96956872/af1cc594-2020-43e9-a111-8013db51ace3)
![on](https://github.com/kwindrem/GuiMods/assets/96956872/84506e5b-7980-44be-a1ca-42769b08a948)

Already tried the following:

- Cerbo firmware downgarde to 3.0
- UI switched to English
- Turned off all power  and rebooted
- Gui mods reinstalled
- 

My system:

- Cerbo GX, FW: v.3.10~12 with Gui Mods v7.68 , SetupHelper 4.42
- GX Tank 140
- Ruuvi tags
- MultiPlus Compact 12/1600/70-16, FW: 505
- SmartShunt 500A, FW: v4.14
- Smart Solar Charger MPPT 75/15, FW: v1.61

Any ideas and thanks in advance!

Arne

**Comment by kwindrem** [comment]
It appears your Multi is not being recognized. by your Cerbo. To confirm this, look in the Device List. If so, this has nothing to do with GuiMods.

If the Multi IS showing up in the device list, try uninstalling GuiMods. If the Multi appears in the overview page then the problem is not with GuiMods.

Let me know.

**Comment by aph70** [comment]
All devices including the Multi do show up in the device list:
![device list](https://github.com/kwindrem/GuiMods/assets/96956872/cc276ea1-cfa9-4f85-b0b1-ddbadd87fb50)

I also can set the Mulit to Load, Invert  or whatever and it will show the correct status.
![inverting](https://github.com/kwindrem/GuiMods/assets/96956872/ed1bb665-d317-4bb0-84c4-c744e787d306)

It also states that it is connected via VE.Bus.
![mulit-connected](https://github.com/kwindrem/GuiMods/assets/96956872/bd95e47b-7295-4594-915d-c3d7001730a0)

GuiMods removed via Setup-Helper I can do power limitation and it shows the selected AC-Modus:
![no_gui_mods_aus](https://github.com/kwindrem/GuiMods/assets/96956872/40ab677c-7a28-4ef3-9f74-9c35d53f4393)
![no_gui_mods_wechselrichter](https://github.com/kwindrem/GuiMods/assets/96956872/596a444a-067b-4cf2-875d-6057b99f9989)

But still the Flow-Screen doesnt show correct status, nor LEDs nor the bullets for power flow (if seen the power flow bullets missing though before when on remote console).

![no_gui_mods_on_limit](https://github.com/kwindrem/GuiMods/assets/96956872/3be3515b-a5e1-47cc-a2bf-687049ccdfe3)

**Comment by kwindrem** [comment]
From the last screen shot, it's apparent that the GX device is not receiving AC and inverter status (off, on, inverting, etc) from the Multi. Also, this is not an issue created by GuiMods.

I'm assuming you have tried rebooting Cerbo and power cycling the Multi.

While using the MK3-USB adapter should be working, it is possible the problem is with using this connection rather than a direct VE.Bus connection between the Multi and Cerbo.

**Comment by kwindrem** [comment]
I can confirm there is a problem connecting the Multi via the MK3-USB on Cerbo.

I will report this as a bug to Victron.
