### ISSUE TITLE
Show additional battery temperatures

### ISSUE THREAD

**Issue by mr-manuel** [kwindrem/GuiMods#168]
Hello Kevin,

is it somehow easily possible to add multiple temperatures from one device to the overview? Like for `dbus-serialbattery` we have up to 5 temperature sensors available (e.g. cells, braker, cable, MOSFETS, ...). I would like to show the battery, cable and MOSFET temperature in the overview.

Currently we put the temperatures under this paths, but the paths can be changed to a more convenient location, if needed:

```
System/Temperature1
System/Temperature1Name
System/Temperature2
System/Temperature2Name
System/Temperature3
System/Temperature3Name
System/Temperature4
System/Temperature4Name
```

![grafik](https://github.com/kwindrem/GuiMods/assets/12592765/4e0e93e4-ab87-446c-b572-40a10d08d795)

**Comment by kwindrem** [comment]
Sorry for the delayed response. It's not simple. 

At the point I populate the temperature tiles, I'm only looking for certain device types. Then within each tile, I'm looking for only one temperature.

The only thing that would be relatively simple is to look for additional temp and temp names and scroll all that are found. This would work OK in a tile width of 1/2 or 1/3 the screen, but it gets crazy if the tiles are smaller especially if a long device name is also present.

**Comment by mr-manuel** [comment]
Would it be an option, that the device/temperature name is scrolling from right to left? I don‘t know, if this is an easy option. Or the temperature boxes are scrolling or changing every x seconds if they are more than the max allowed.

**Comment by kwindrem** [comment]
The temperature tiles get pretty small:
![Screenshot 2023-07-18 at 3 16 43 PM](https://github.com/kwindrem/GuiMods/assets/58538395/4f6b408c-be73-4bb4-9b9a-b927aff5d956)

![Screenshot 2023-07-18 at 3 23 13 PM](https://github.com/kwindrem/GuiMods/assets/58538395/f2bebf05-6472-4659-a326-8dbc8093be92)

The name and temp/humidity areas both scroll when space is limited like in the screen shots above.
In addition, There is a device name, plus the temperature name.

So accommodating additional temperatures will get pretty busy.

I feel that this is too much to try to cram into a small space and that most users would probably be confused by such information. I would think this type of information would be useful when commissioning a system, but not during daily operation.

There is an overview page that provides more space but it too shares space with tanks and digital inputs. The temps column looks like this:
![Screenshot 2023-07-18 at 3 24 46 PM](https://github.com/kwindrem/GuiMods/assets/58538395/e8c40c2c-871d-4b23-90b8-63cc0dcd0304)

Scrolling sensor name and temperature  in this page might be OK, but only if there is space so the temps each get two lines as shown.

**Comment by mr-manuel** [comment]
Ok thanks. Since I have only the battery temperature there is more than enough space. But I will write a little script that act as temperature sensor that reads the value I need.

**Comment by mr-manuel** [comment]
For anyone else interested: [venus-os_dbus-mqtt-temperature](https://github.com/mr-manuel/venus-os_dbus-mqtt-temperature)

![temperature_pages_guimods](https://github.com/kwindrem/GuiMods/assets/12592765/d989f4f6-dd6b-49a0-8071-488f10e612d1)
