### ISSUE TITLE
Guimods file set incomplete

### ISSUE THREAD

**Issue by svalbard2** [kwindrem/GuiMods#171]
CerboGX fw ver 3.10 - 17

GuiMods 7.72

Incompatible?

**Comment by kwindrem** [comment]
Yes. Lots of changes in ~17. Testing a new version of GuiMods now.

**Comment by svalbard2** [comment]
Installed back to 3.01 on the CerboGX. Then all OK...

**Comment by kwindrem** [comment]
Fixed in v7.73

**Comment by svalbard2** [comment]
Hi, something wrong with latest version 8.03? Now just a blank display?


Regards Heinrich
