### ISSUE TITLE
missaligned flow dots to flow lines on vertical flow

### ISSUE THREAD

**Issue by virtuvas** [kwindrem/GuiMods#172]
K.,

apologies if it sounds stupid, it's a tiny silly mistake that now that I notice I see it all the time and is getting annoying for no reason...

![image](https://github.com/kwindrem/GuiMods/assets/17377407/58ddbb4c-3ff0-45d3-88ab-125f26432f97)
on the above image the vertical flow line is nice and aligned BUT the flow dots are around a pixel off to the left.
All horizontals are fine...
I'm on a rpi 3B+ running release 3.0 Venus OS Large, on the "official" 8in 800X600pix display.

Anyone experiencing this? else maybe something wrong on my config.txt (although I doubt it tbh!)

thanks for all the hard work you're putting in this!

V.

**Comment by kwindrem** [comment]
I see this on my Cerbo also and also with the stock flow overview although not as bad and I believe it's been that way forever. I have no idea what causes this but suspect the precision in positioning the flow lines. Not much I can do about it unfortunately.
