### ISSUE TITLE
multiple Battery Board

### ISSUE THREAD

**Issue by StephBoat** [kwindrem/GuiMods#174]
Hi kwindrem,

is there any option to show more than one Battery on the main screen?

i use the cerbo + BMV-702 + an Smart shunt on my sailingboat and would like to get an overview of all the battery-data so BMV702 + extra voltage measurng and shunt 2 with extra voltage measuring - so have an overview on 4 Battery-packs.

Would that be possible do to?

**Comment by kwindrem** [comment]
No this is not an option and unfortunately there is no space for a generic solution. Others have modified the page to show additional battery information at the expense of other information such as omitting the AC input tile.

Also, additional batteries do not integrate well enough to provide a flow to other parts of the system (the lines with moving dots).

I realize that multiple batteries are common in marine systems. Many also have completely different DC electrical systems with DC-DC chargers linking them. A solution within Venus OS will need to come from Victron and is probably not likely.

A while back, I saw a Grafina implementation for a boat that did show two electrical systems with flow information. That's probably the direction system integrators and DIY projects need to go. Of note, this was formatted for a much larger screen and would not have been readable on the 5 or 7 inch screens typically used for Venus OS.
