### ISSUE TITLE
One DC System device displayed but multiple present

### ISSUE THREAD

**Issue by proptied** [kwindrem/GuiMods#175]
Firmware: `v3.10~21`
SetupHelper: `v4.42`
GuiMods: `v7.75`
ExtTransferSwitch: `v2.24`

I have multiple DC System devices installed, but only one device is listed on the "DC System Detail" screen.

Is this page supposed to list each of them in a row, like the "other DC devices" table?

**Page:**
![image](https://github.com/kwindrem/GuiMods/assets/22583218/cc3a35af-3341-4ee1-87b8-fd8300f2f09e)

**Devices:**
![image](https://github.com/kwindrem/GuiMods/assets/22583218/9e5a9616-9a2c-46d8-9fdc-03840df7f9f4)

![image](https://github.com/kwindrem/GuiMods/assets/22583218/571a01c7-47a3-4162-88e6-062e87a57385)

**DC System 1 ("24V Source")**
![image](https://github.com/kwindrem/GuiMods/assets/22583218/c01fdcd0-3154-477d-a6fb-f14ca5d544a8)

**DC System 2 ("24V Load")**
![image](https://github.com/kwindrem/GuiMods/assets/22583218/e7cc7818-d835-48c1-b15d-ff48ce37854d)

**Comment by kwindrem** [comment]
Yes, I would expect the two .dcsystem. devices would appear in the upper part of the table.

It is possible the second row in the system table is hidden. See if you can scroll the table to it by swiping. If so, I will attempt to adjust the table sizing logic.

**Comment by proptied** [comment]
Ah! You nailed it... I swiped in the upper table and it scrolled to the second one. Thanks!

**Comment by kwindrem** [comment]
I had a bug in the logic that sizes the tables. Should be fixed in v7.77
