### ISSUE TITLE
20230717162050 v3.01 GUIMods 7.77 incompatible

### ISSUE THREAD

**Issue by albundy0815** [kwindrem/GuiMods#178]
Hi, today I've updated to 3.01 (to be honest, I don't know how to find out the 3.01~xx)
I can only see the date of the release and GUIMods shows me, that it's incompatible. Is this already known?
![image](https://github.com/kwindrem/GuiMods/assets/97403164/f168645c-ea82-41c5-b72c-bd9264615947)
![image](https://github.com/kwindrem/GuiMods/assets/97403164/91aa7663-cdcd-4ee1-8d3e-cb5a8f471814)

**Comment by albundy0815** [comment]
I had a look on:
https://github.com/kwindrem/GuiMods/issues/119
and this works for me as well. Uninstalled GUIMods, reboot and installed again.

Nevertheless... could please someone give me a hint how to see the Build-Number? I mean the Venus OS v3.xx~**%%**

**Comment by kwindrem** [comment]
A number following ~ indicates a pre-release (otherwise know as release candidate) version. v3.01 is released so there will be no ~ and no number following it.
