### ISSUE TITLE
Installed but no setup helper

### ISSUE THREAD

**Issue by paulmc28** [kwindrem/GuiMods#179]
I just did a blind install, package manager is installed but it didn't install setup helper by default. It is listed in the inactive packages, but if I try to activate it nothing happens.

**Comment by kwindrem** [comment]
That's very strange. If you are seeing PackageManager in the menus, then SetupHelper is definitely installed, or at least the PackageManager service is still present from a previous install.

If you have not done so already, try rebooting.

If that does not work, scroll to the bottom of the Package manager menu and select Initialize PackageManager and do the Initialize.

**Comment by paulmc28** [comment]
Tried it. Just hangs at ...initializing and restarting.

**Comment by kwindrem** [comment]
Did you reboot after the initialize?

Next would be to try the blind install again. Make sure you remove the USB stick when the GX device BEGINS its reboot.

Last thing to try would be a blind uninstall, then a blind install of SetupHelper.

**Comment by paulmc28** [comment]
I have tried all of this multiple times.

The first time I installed setuphelper it was in the active list. Then I mistakenly removed it and it has not worked since.


Thanks for all the help.

**Comment by kwindrem** [comment]
I found a bug in Package manager. should be fixed now in SetupHelper v4.43. You will probably need to do a blind install again.

**Comment by paulmc28** [comment]
Ran the new install, same results.

**Comment by kwindrem** [comment]
Did you download the new blind install from GitHub?

**Comment by paulmc28** [comment]
I did.

**Comment by kwindrem** [comment]
I will need to see the logs in order to help further. Unfortunately without PackageManager running you'll need ssh access to the GX device to gather the log files.
