### ISSUE TITLE
Installation fails on Venus OS v3.10~8

### ISSUE THREAD

**Issue by jonofe** [kwindrem/GuiMods#180]
The installation of GuiMods fails on Venus OS v3.10~8.
As I could not identify the reason while trying to install via the gui, I tried to execute the "setup" via console with the following result:

root@raspberrypi2:/data/GuiMods# ./setup
--- starting setup script v7.78
creating file set for v3.10-8
ERROR v3.10-8 dbus_systemcalc.py no replacement file
ERROR v3.10-8 OverviewGeneratorEnhanced.qml no replacement file
ERROR v3.10-8 startstop.py no replacement file
ERROR v3.10-8 PageGenerator.qml no replacement file
ERROR: incomplete file set for v3.10-8 - can't continue

Any suggestions how to fix this?

**Comment by kwindrem** [comment]
Please upgrade Venus OS to the latest beta (currently v3.10~25).

When I upgrade a package, I don't always maintain support for older betas. If you are running beta software it is a good idea to keep it at the current release candidate. Beta software can have bugs and/or have incomplete features.
