### ISSUE TITLE
Changing the names of tiles

### ISSUE THREAD

**Issue by ChillV2L** [kwindrem/GuiMods#182]
First of all thanks for all your hard work on this gui mod project its great 
wondered if you could help me with changing the names of the tiles  on the VRM and/or the remote console
![image](https://github.com/kwindrem/GuiMods/assets/121485342/69d38822-6659-436b-b983-e57b829a0fe6)
for example i would like to change the name of "GRID "  to "powerwall/grid" or "generator" to "V2L " is this already possible but if not maybe a idea for future updates 
many thanks Chris

**Comment by kwindrem** [comment]
Unfortunately, the VRM menus are completely separate from the GX devices's menu system. I don't even know where this code is or if it can be modified.
