### ISSUE TITLE
Increase maximum relay count

### ISSUE THREAD

**Issue by usairforce456** [kwindrem/GuiMods#184]
This is more of a question, than a issue, or feature request. How hard would it be to increase the maximum number of relays from 6 to say 10 or more?

**Comment by kwindrem** [comment]
If you are talking specifically about the GUI, the relay overview would need to change significantly. 6 relays maxes out the screen so there would need to be a way to show a second page. Sideways swipes on overviews are reserved for changing overviews so I'm not sure what could be done here. I suppose a second relay overview could be added for the additional relays. Also, the relay settings pages would need to expand but that's simply a matter of adding more items. The menu does get pretty long but it's only for setup so ...

I'm not sure what the limit to adding additional relays would be. On a Raspberry PI, additional pins could be employed but conflicts would exist with other functions like SPI and I2C.
