### ISSUE TITLE
Venusos 3.10~38 Guimod 8.04 not compatible?

### ISSUE THREAD

**Issue by pieterjanvz** [kwindrem/GuiMods#189]
i get the error Incompatible in setuphelper after Upgrading venusos to version 3.10~38

![Schermafbeelding 2023-09-09 165853](https://github.com/kwindrem/GuiMods/assets/81514282/4296a767-69f1-4610-a4d6-43c1bd111952)

**Comment by pieterjanvz** [comment]
after a restart , and retry i get this message:

![Schermafbeelding 2023-09-09 174124](https://github.com/kwindrem/GuiMods/assets/81514282/a9a8b690-83eb-42de-9845-5e4a891dbfb6)

**Comment by kwindrem** [comment]
fixed now in v8.05

**Comment by kwindrem** [comment]
If you are still having problems, wait a while -- maybe 30 minutes or more. It sometimes takes a while for updates to GitHub to propagate through the internet.

**Comment by pieterjanvz** [comment]
THANKS , its fixed , you are the best.

![Schermafbeelding 2023-09-09 182253](https://github.com/kwindrem/GuiMods/assets/81514282/22d8b943-f797-42ce-9263-9696aa5257f2)
