### ISSUE TITLE
Request - More than 6 relays

### ISSUE THREAD

**Issue by JimmyM01** [kwindrem/GuiMods#197]
Is it possible to have more than 6 relays? I'm interested in controlling them with NodeRED.

Thanks, Kevin

**Comment by kwindrem** [comment]
There have been discussions on the Victron forum about expanding the number of relays, so yes it is possible. Please look at those threads.

As far as displaying more than 6 relays on my relay overview -- no. The columns would get too narrow to provide any meaningful information (names, button labels, etc would be truncated)
