### ISSUE TITLE
Input limit visibility

### ISSUE THREAD

**Issue by jsalbre** [kwindrem/GuiMods#198]
Would it be possible to make the AC input limit visible on the AC tile even when there is no active AC input? It would help avoid plugging into a low amperage outlet with the limit set high.

**Comment by kwindrem** [comment]
I can do it but will need to modify my code to keep the Limit: line at the bottom of the tile. I'll put it on the TODO list.

**Comment by jsalbre** [comment]
Awesome, thanks! You need a “tip jar” or something.JeremyOn Oct 31, 2023, at 14:17, kwindrem ***@***.***> wrote:﻿
I can do it but will need to modify my code to keep the Limit: line at the bottom of the tile. I'll put it on the TODO list.

**Comment by kwindrem** [comment]
Done
