### ISSUE TITLE
Cerbo 3.20~26 unable to function with Guimods

### ISSUE THREAD

**Issue by andyfoulger** [kwindrem/GuiMods#207]
Hello - Seems like the latest Cerbo update doesn't work with Guimods. Can you please update?

**Comment by kwindrem** [comment]
GuiMods v8.21 is running on my Cerbo GX v3.20~26. I'd need to take a look at the logs to figure out why it's not working for you.

**Comment by andyfoulger** [comment]
Okay great. I reverted back to v3.20~10 and it's back working. I'll need to reupdate. I did notice that I didn't have the package manager when I upgraded to 26. Do you know if I have to install locally again when I do that?

**Comment by kwindrem** [comment]
Package Manager works in ~26 so you should not need to install from the command line.

I did find one issue where the Gui is not being restarted following an update. Working on an update to SetupHelper to fix that now.

**Comment by andyfoulger** [comment]
Awesome. I'll update after you give the all clear to try.

**Comment by kwindrem** [comment]
SetupHelper v5.14 is available now that fixes the GUI restart problem.

**Comment by andyfoulger** [comment]
Thank you. It still doesn't work. After update, setuphelper doesn't install. I checked the version under the previous version of venus and I'm on 5.14. Can you think of any reason that it wouldn't install. I can't see anything in the settings for a package manager.

**Comment by kwindrem** [comment]
Working on a problem in SetupHelper

GuiMods is not yet compatible with v3.20~27. Working on that too.

**Comment by andyfoulger** [comment]
Awesome. I'll wait to try it until you give the all clear.

**Comment by andyfoulger** [comment]
Verified that the patches have fixed it. All working on 27 now.
