### ISSUE TITLE
Integrate Cerbo GX with data to/from a nearby Zigbee network?

### ISSUE THREAD

**Issue by kjel-siv** [kwindrem/GuiMods#209]
I have recently joined this amazing community and are still discovering the features of my new Victron Cerbo GX with GuiMod and the Node Red software. 

In my boat I want to integrate the Victron Cerbo GX with my Zigbee network to be able to use e.g. the geofence feature in the Cerbo to set the alarm features in the Zigbee world, and vis-a-versa be able to show eg. the Temperature data from the Zigbee sensors on the Cerbo GX display.

Has anybody done this already or do anybody have a clue where to start this journey?

**Comment by kwindrem** [comment]
Welcome to the Victron world.

What you are suggesting is not something GuiMods can accomplish. Zigbee integration will require some significant changes to Venus OS as it will affect many different sub-systems. Please post this as an question/idea in the Victron Community forum modifications section:

https://community.victronenergy.com/spaces/31/index.html

**Comment by kjel-siv** [comment]
Thanks for the swift reply and advice :-) 

Done!
