### ISSUE TITLE
V3.20~33 white screen

### ISSUE THREAD

**Issue by thomasinaz41213** [kwindrem/GuiMods#212]
I'm sure you're probably working on it already, but just in case... updated to 3.20~33 and got white screen. I'll roll back to 3.13 for now.

**Comment by kwindrem** [comment]
I have seen this a couple of times on first boot after updating firmware. A reboot restored the GUI. 

I was able to reproduce the problem and it has something to do with SetupHelper (PackageManager). Looking into the cause and will fix it. 

For now, just reboot after a firmware update if running any packages that use SetupHelper!

**Comment by kwindrem** [comment]
Should be fixed now in SetupHelper v5.16
