### ISSUE TITLE
GuiMods glitch - suddenly not working

### ISSUE THREAD

**Issue by lfhoward** [kwindrem/GuiMods#215]
Dear Kevin,

At some point last night or this morning GuiMods had some kind of problem and is no longer functioning. Perhaps a bad auto-install? I used SetupHelper to remove it and reinstall, and rebooted after each change. I cannot get it to work but I think you probably can! Maybe an older version of GuiMods would get me up and running. 

Here are some screenshots from my system, which is a Raspberry Pi 3 running Venus OS version 3.12. 

![IMG_8496](https://github.com/kwindrem/GuiMods/assets/99151873/f0521a25-525c-45a8-9fb2-bece3c86e5ef)

![IMG_8497](https://github.com/kwindrem/GuiMods/assets/99151873/c35e06be-34d6-4828-bfdc-1fd76c21b464)

![IMG_8498](https://github.com/kwindrem/GuiMods/assets/99151873/3dfceb0e-0e5f-42b8-8f4a-5b5dc3afe551)

Thanks for your help!

**Comment by kwindrem** [comment]
I have found the problem and will have a new version out later today. Thanks for reporting.

**Comment by lfhoward** [comment]
Thanks Kevin. Have a good evening.

**Comment by kwindrem** [comment]
Should be fixed now: v8.26

**Comment by lfhoward** [comment]
> Should be fixed now: v8.26

Yes, working perfectly and it even preserved my settings. Thanks again.
