### ISSUE TITLE
Proper upgrade process

### ISSUE THREAD

**Issue by tingles2233** [kwindrem/GuiMods#216]
Hi new user here… love GuiMods

I wanted to check and see what the “official” process for updating/upgrading the cerbo and/or guimods upgrades come out..

Should one always upgrade the cerbo version first then guimods via packagemanager? 

Is there a link to a page saying which combination of guimods versions and cerbo versions are compatible to ensure we keep our system running smoothly? 

Thanks in advance

**Comment by kwindrem** [comment]
The upgrade order really doesn't matter. 

When a firmware update occurs, any installed modifications are wiped out, but packages managed by SetupHelper are stored in an area that survives a firmware update. The packages are automatically reinstalled after a firmware update.

Packages are designed to be installed on most recent firmware versions without downloading the package again from GitHub. The one exception:  When a new firmware version is released, the package may not contain compatible files. In this case an install attempt fails. I try to stay on top of firmware versions so a new package version is normally available to support the new firmware within a day or two.

PackageManager can be set to automatically download and install new package versions if desired. It is recommended that on a mission critical system firmware updates and package updates from GitHub be turned off and managed manually when there is time to back up to the previous version should problems occur. That said, many users simply leave all automatic updates turned on and are usually fine.
