### ISSUE TITLE
v8.27 -> No file set for 3.11

### ISSUE THREAD

**Issue by SergioRius** [kwindrem/GuiMods#217]
I suppose it automatically updated to v8.27, and guimods has completely deactivated.
The packages screen shows the message on the topic.
I don't think Venus v3.11 is an obsolete version.

**Comment by EntwicklungScuddy** [comment]
Same here. I downgraded to v8.24. Everything is fine again. The same happend on a v3.12machine.

**Comment by kwindrem** [comment]
I am not seeing a problem with GuiMods v8.27 on Venus OS v3.11 or v3.12.
There was certainly a problem with v8.26 but v8.27 was the fix.

**Comment by SergioRius** [comment]
> I am not seeing a problem with GuiMods v8.27 on Venus OS v3.11 or v3.12. There was certainly a problem with v8.26 but v8.27 was the fix.

I don't understand. I always had the problem with the v8.27. This version doesn't want to install:
![imagen](https://github.com/kwindrem/GuiMods/assets/1693727/7366c0d9-cec2-4372-9804-3da47582425f)
![imagen](https://github.com/kwindrem/GuiMods/assets/1693727/d14c6d5a-a8f9-4544-8fc5-3862c273ba7e)

**Comment by thomasinaz41213** [comment]
I have had this happen a few times. Have you tried rebooting Venus? Usually fixes it for me. If it was a FileSets issue it would usually just display "no FileSets".

**Comment by kwindrem** [comment]
What GX device are you running (Cerbo, etc)?

I can not duplicate the issue here. I will need log files to diagnose further.

If you have ssh access:

tail -50 /data/log/SetupHelper | tai64nlocal

Please zip logs before posting here.

Use the PackageManager Backup function to store logs on a USB stick. This creates logs.zip which you can post here.

You might try downloading and installing GuiMods again. Using PackageManager is fine.

You can also move on to Venus OS v3.12 which is the current release.

**Comment by Freensman** [comment]
Hey all

I facing the same problem. Tried up and down with 3.13 and 3.10 and 3.20 and GM 8.28. 

same message on all tries: "no file set for 3.11" (3.13 etc.)
I uninstall setup helper, uninstall guiMods ect. 
Reinstall all, but GuiMods is still there.

No success. 

Attached the asked logfile:

tail -50 /data/log/SetupHelper | tai64nlocal


[no_file_set_log.txt](https://github.com/kwindrem/GuiMods/files/13726522/no_file_set_log.txt)

![Bildschirmfoto 2023-12-20 um 12 03 39](https://github.com/kwindrem/GuiMods/assets/96165265/167dc58e-e47f-4040-a174-d4ce3b01f77a)


Thanks for help. Freens

**Comment by kwindrem** [comment]
Freensman, your issue is that in fact a new version of Venus OS was just released and I need to update GuiMods. I'll do that now.

**Comment by Freensman** [comment]
Thanks a lot for your fast answer and help. 

Space is still available. 

It seams I can not uninstall GuiMods from the Setup Helper:

![Bildschirmfoto 2023-12-21 um 08 04 09](https://github.com/kwindrem/GuiMods/assets/96165265/735f5fcc-c980-43ca-9625-d963fdd5cd71)

Is it possible without problems to just delete the folder directly, and reinstall after?
Or is there a direct possibility to download via ssh again?
(sorry I'm not a coder, just have basic knowledge about it)

![Bildschirmfoto 2023-12-21 um 08 05 47](https://github.com/kwindrem/GuiMods/assets/96165265/5e85fcba-6f87-43d6-83fd-6ed5b1a56349)


Thanks so much - Freens

**Comment by kwindrem** [comment]
Looks like PackageManager is stuck for some reason or the downloading message would go away.

Reboot and see if you can download. 

If a package is uninstalled (and in our case GuiMods is uninstalled), you can delete the package folder but you should then perform the Initialize PackageManager (at the bottom of the main PackageManager menu).


You can download from the command line using wget. That procedure is in the SetupHelper ReadMe.

**Comment by Freensman** [comment]
Thanks for this. 

I tried various things, finally the following worked.

-> uninstall and reinstall SetupHelper over ssh-> don't solve issue
-> unistall GuiMods via SetupHelper ->  don't solve issue
-> delete GuiMods folder over ssh -> not able to reinstall over SetupHelper
-> uninstall SetupHelper over ssh
-> delete SetupHelper Folder over ssh
-> reinstall SetupHelper over ssh
-> SetupHelper runing 
-> GuiMods running without any install or download.

Thanks so much for your help and very appreciated work.

**Comment by SergioRius** [comment]
Please @kwindrem , can you tell me what I have to do to make Guimods work again?
Thanks.

**Comment by kwindrem** [comment]
SergioRius, without logs, there's only so much I can do. Here are some shotgunning steps you may or may not have tried yet:

Use PackageManager to download GuiMods again and try the install manually.

Uninstall amy modifications authored by others then pdate the Venus OS firmware: switch to the stored backup then use the online update to install the firmware again. Do not simply switch back to the existing stored version in the backups section.

If you get GuiMods back, uninstall it, then install one of the other modifications, then install GuiMods again. Repeat the GuiMods uninstall, install other modification, reinstall GuiMods for each of the packages you are using. This will identify any conflicts between modifications.

Note that it is not necessary to do these modification steps with my packages, just those authored by others.

I will need detailed explanations or better yet the log files from a failed GuiMods install.

You can put the logs on a USB stick from using the PackageManager Backup function. It generates a logs.zip file on the USB stick you can post here.
