### ISSUE TITLE
Request for battery action buttons 

### ISSUE THREAD

**Issue by sarah1331sarah** [kwindrem/GuiMods#218]
Would it be possible to add buttons inside the battery detail screen 
![image](https://github.com/kwindrem/GuiMods/assets/112808604/7ee0be17-bf1b-4d77-9dcf-5b352368f23d)

battery selection buttons 
“Force discharging off” and “force charging off”
![IMG_0673](https://github.com/kwindrem/GuiMods/assets/112808604/58796f85-42e3-4b77-b4e1-9a16eb474b61)

Am not sure if your going to discontinue this project 

thanks for reading

**Comment by kwindrem** [comment]
There really isn't space in the battery detail to add buttons. I also don't see these parameters anywhere in the stock Victron menu code. Is this a third-party BMS?

As I have said elsewhere, GuiMods is going to be phased out when gui-v2 is released and GUI v1 is no longer available. It is not yet clear if or how gui-v2 can be modified but minds better than my own are working on how this might be possible.

**Comment by sarah1331sarah** [comment]
It’s in https://github.com/Louisvdw/dbus-serialbattery
The driver but I understand

**Comment by sarah1331sarah** [comment]
I don’t want to sound a complete a-hole bud but is this something you could do or is it impossible? I will try to figure it out but am struggling it would save me running wires are relays etc

**Comment by kwindrem** [comment]
Not really possible. Plus with the new GUI coming I'm not all that motivated to makeing changes to GUI v1 overview and detail pages.

**Comment by sarah1331sarah** [comment]
I totally understand thanks again
