### ISSUE TITLE
What does the S and C mean on the DC System details page

### ISSUE THREAD

**Issue by Stoom** [kwindrem/GuiMods#220]
Like the title says, I cannot for the life of me figure out what these are. Looking at the code it looks like these are just default values?

**Comment by kwindrem** [comment]
S = Supplying (power leaving the system tile)

C = Consuming (power entering the system tile)

The S should only appear if you have set a maximum DC System charge value for the gauge.

Remember that DC System is a collection of any power source or load so I had to accommodate this even though typically DC System is only loads.
