### ISSUE TITLE
No FileSets Venus beta V3.20-45

### ISSUE THREAD

**Issue by thomasinaz41213** [kwindrem/GuiMods#226]
No FileSets for Venus os v3 20-45

**Comment by kwindrem** [comment]
Testing now.

BTW, ExtTransferSwitch is being merged into GuiMods due to all the overlap in modified files.

**Comment by Zeoic** [comment]
I am seeing the same message on my pi

**Comment by kwindrem** [comment]
Please be patient. I'm working on the situation. Many changes that all need to be checked across multiple firmware versions. Will release tomorrow.

**Comment by Zeoic** [comment]
> Please be patient. I'm working on the situation. Many changes that all need to be checked across multiple firmware versions. Will release tomorrow.

Thanks for looking into it! This looks like a super handy package. Appreciate all the work you put into all these!

**Comment by kwindrem** [comment]
Now fixed

GuiMods now includes the functionality of ExtTransferSwitch package. ExtTransferSwitch will automatically be removed when installing the new GuiMods.
