### ISSUE TITLE
v10.2 removes v3.20 beta file sets

### ISSUE THREAD

**Issue by kwindrem** [kwindrem/GuiMods#229]
I removed the v3.20~... file sets from GuiMods as of v10.2 which supports the official release of v3.20.

Victron recommends an immediate update to the released version when available. I realize that some users may require time to update their systems so if you need a previous beta, set the branch/tag to v10.1.

Do not forget to reset it to latest once you do upgrade firmware so you'll get future updates.

**Comment by Ritterlanzelot** [comment]
Thank you so much for your work - unfortunately, after updating venus to 3.20,  update of GUimods to v10.2 stops at "checking for downloads and installs". Manual update/download/install, several reboot, initialize packageManager etc does not help

**Comment by kwindrem** [comment]
The message "checking for downloads and installs" is the idle message when downloads and auto installs are on. This does not indicate a download or install failure.

What is shown in the Active Packages screen and in the detail page for GuiMods?

**Comment by Ritterlanzelot** [comment]
Thanks for your attention - available should be 10.2, installed and stored is 10.0 (screenshots attached). After switching to download an confirming with "proceed", nothing happens ...
![Screenshot_20240214_070655_Chrome](https://github.com/kwindrem/GuiMods/assets/66508010/96f0450c-f2a2-488b-a2f8-570d91b256cc)
![Screenshot_20240214_070652_Chrome](https://github.com/kwindrem/GuiMods/assets/66508010/16698420-5f87-4406-83c9-e17bb213bbdf)
![Screenshot_20240214_070643_Chrome](https://github.com/kwindrem/GuiMods/assets/66508010/5f6a953e-876c-4e36-8ae7-142fd4e201fe)
![Screenshot_20240214_070505_Chrome](https://github.com/kwindrem/GuiMods/assets/66508010/31f07c94-765c-4a12-a104-89393652786d)

**Comment by kwindrem** [comment]
This is very strange indeed. I tried to reproduce what you are seeing but could not.

I would like to take a look at the logs. If you have ssh access the logs of interest are:

/data/log/SetupHelper
/data/log/PackageManager/current

If you don't have sss access, you can capture the logs to removable media via the backup mechanism in PackageManager.

**Comment by Ritterlanzelot** [comment]
Sure - where can i upload or send the logs?

**Comment by kwindrem** [comment]
Just post the zip file here. Thanks. (Please do not post plain text if you can avoid it.)

**Comment by Ritterlanzelot** [comment]
Solved! There was a folder "GUIMods-Temp" which obviously blocked. I deleted it, and after that the install worked as expected. Thank you for your attention and all your work with GUImod, i appreciate it very much!

**Comment by kwindrem** [comment]
Thanks. Useful information. PackageManager should be tolerant of such situations. I'll look into it.

**Comment by Ritterlanzelot** [comment]
Just4you to know, there was no folder named "/data/log/setupHelper" ...

**Comment by Ritterlanzelot** [comment]
[Logs.zip](https://github.com/kwindrem/GuiMods/files/14292601/Logs.zip)
As requested!
