### ISSUE TITLE
GuiMods downloading but not installing

### ISSUE THREAD

**Issue by JohnnyOckerman** [kwindrem/GuiMods#230]
Hi,
I’ve successfully installed the setup helper and see Package Manager at the bottom of the Settings menu. 
I can add GuiMods from inactive to active packages.  However, after downloading the GuiMods package the Install button doesn’t become accessible.  The version in the GitHub field is visible but not in the Stored field.
Any advice to get the GuiMods installed?
Thank you,

**Comment by kwindrem** [comment]
The blank "stored" version indicates GuiMods is not on the system. You need to download if from GitHub. You can do this by turning on automatic downloads and then automatic install to get it to actually install. Or you can tap on GuiMods in the active package list and do the operations manually. Once downloaded, the install button should become active.

**Comment by JohnnyOckerman** [comment]
Hi, thx a lot for the swift reply.  Unfortunately, the automatic nor manual download is successful.  When clicking Proceed with manual download It says “… downloading” but Stored field an Install button remain empty/inaccessible.

**Comment by kwindrem** [comment]
Try a reboot if you have not done so already.

Which SetupHelper version is installed?

Is there anything in your internet connection that could prevent the download?

I'd need to take a look at the logs.

Use the backup function inside PackageManager. That will create a logs.zip file on removable media which you can post here.

**Comment by JohnnyOckerman** [comment]
No success after multiple reboots.
No idea about an internet issue.
Cerbo GX Firmware  version: v3.20
SetupHelper version: v6.6
logs.zip attached.
[logs.zip](https://github.com/kwindrem/GuiMods/files/14310255/logs.zip)

**Comment by JohnnyOckerman** [comment]
Hello,
Is the logs.zip helpful to identify the issue?
Under package manager I read something like file(s) not available. 
Thank you,

**Comment by JohnnyOckerman** [comment]
Hello,
I did reset my Cerbo GX to factory settings and did reinstall SetupHelper v6.6.
Unfortunately the issue remains unresolved.  After downloading the GuiMods, I see a brief message "downloading GuiMods..." but the Install button remains greyed out.
Thank you,

**Comment by kwindrem** [comment]
SetupHelper v6.6 has a problem that prevents downloads if there is no package already stored on the GX device.

SetupHelpver v6.8 is the current version and fixes this issue. You need to upgrade SetupHelper.

**Comment by JohnnyOckerman** [comment]
Awesome, your advice settled the issue. 
Thanks so much.
