### ISSUE TITLE
GuiMods fails to install after VenusOS 3.20 Update

### ISSUE THREAD

**Issue by petertmac** [kwindrem/GuiMods#231]
I updated VenusOS on my Raspberry Pi 3B+ today and after a reboot I lost GuiMods. Looking at setup helper it shows a message under GuiMods as “no file set for v3.20”. I tried updating to v10.3 of GuiMods and same error. I rolled back to VenusOS v3.14 which was working, however it updated to v10.3 and I have the same error. Any suggestions on how to recover?

**Comment by albundy0815** [comment]
great, that I'm not the only one. I was wondering if it is a problem on my side. Because just before I've updated to 3.20

**Comment by petertmac** [comment]
Correction- typo on my part. The upgrade was to 3.20.

**Comment by ckvsoft** [comment]
It's probably a general problem.
I have the same problem here.

**Comment by Bosode** [comment]
yeah - same at my installation. early this morning fallback to Victron default layout and menu structure.

**Comment by dersch81** [comment]
yes same here

**Comment by kwindrem** [comment]
Sorry for the install failure. Somehow the version I checked in had a corrupted file set for v3.20.

V10.4 is being pushed as I write this

**Comment by pcmedicsd** [comment]
Yahoo! thanks for the quick fix Kevin :)

**Comment by albundy0815** [comment]
@kwindrem thank you so much for support and also for the GUIMods. Today I've seen, that the default VenusOS is ~1% and your addon gives me additional 99% at user experience ;-)

**Comment by petertmac** [comment]
Amazing, woke up this morning and the fix is done. Thanks Kevin.

**Comment by Bosode** [comment]
@kwindrem Thank you for your amazing job to build an update this great tools and share them with us ***thumbs up**
