### ISSUE TITLE
No file set for v3.14

### ISSUE THREAD

**Issue by svsoleil** [kwindrem/GuiMods#232]
![IMG_6822](https://github.com/kwindrem/GuiMods/assets/160285635/b01563c9-76cf-4635-bc0a-2513bce0a656)

**Comment by kwindrem** [comment]
Looks like GuiMods v10.3 does have a corrupt file set for Venus OS v3.14. I suggest you update to v10.4. 

There's a bug in PackageManager that disabled the Download button after the no file set error but you can get around this by stepping to a previous or next package then back again, or going back one menu an entering the package editor menu again.

**Comment by svsoleil** [comment]
All good.
