### ISSUE TITLE
Only Single Phase system is shown

### ISSUE THREAD

**Issue by CarstenFeuls** [kwindrem/GuiMods#240]
Hello
When I click on the System Startscreen on the Multiplus/Inverter Icon I can only see the Inverter details from Phase 1. The values from Phase 2 and 3 are missing.
The Bargraph show all three Phases.
I have installed Guimods v10.10 and the Cerbo Firmware 3.22
I don't know when this Issue apears with the Latest Cerbo Release or a Guimods update but it worked before.

**Comment by kwindrem** [comment]
I see the problem in my code and will get an update out ASAP.

Thanks for reporting
