### ISSUE TITLE
Guimods missing in Venus 3.30

### ISSUE THREAD

**Issue by drtinaz** [kwindrem/GuiMods#242]
Updated to firmware 3.30 and guimods shows as installed in the active packages list, but is missing from display & language menu. Gui is oem. Gui restart or system reboot does not remedy the problem.

Setuphelper 7.6
Guimods 10.15

**Comment by kwindrem** [comment]
My bad. I was checking remove on the last package in the list. Removing one in the middle does corrupt the list because PackageManager is crashing and restarting in the middle of the operation. v7.7 coming soon.

**Comment by blieven1** [comment]
I'm having the same issue

Used Setuphelper 7.7 to install Guimods 10.15

![image](https://github.com/kwindrem/GuiMods/assets/12248588/3bf7dc21-16b2-460d-a3c8-9c379bcfa9a4)

Shutdownmonitor is available in the menu but guimods not

Kind regards,
B

**Comment by kwindrem** [comment]
Noted. Working on the problem now. 

There's a bug with automatic downloads that causes PackageManager to crash. For now, please turn off auto downloads.

**Comment by blieven1** [comment]
Hi, I checked but automatic downloads are already off. Tried uninstalling and redownloading but nothing helps

**Comment by drtinaz** [comment]
When this happened to me yesterday I was able to get guimods installed by reverting to v6.10 of setuphelper and rebooting twice. Then went back to latest v.

**Comment by kwindrem** [comment]
SetupHelper v7.8 should be the fix. I would recommend downloading and installing GuiMods and ShutdownMonitor manually to make sure everything is installed properly.

**Comment by blieven1** [comment]
Thanx! It works now

**Comment by kocki2** [comment]
It's working again:
GuiMods 10.17
SetupHelper 7.9

Thanks,
Gerd

**Comment by Albarge** [comment]
I just updated SetupHelper from v7.8 to v7.9 and GuiMods from v10.16 to v10.17 then VenusOS from v3.22 to v3.30 and had the same problem, both BatteryAggregator and GuiMods were uninstalled like before after the Venus update.

![Screenshot_20240322-130709](https://github.com/kwindrem/GuiMods/assets/98849340/f5f0f5c2-db9b-4ff1-ac81-eada79109c26)

**Comment by kwindrem** [comment]
I have tried several times to reproduce this problem but so far the automatic install is working for me.

I would appreciate the logs from your system:

Insert a USB stick into the GX device, go to Settings / Package manager / Backup & restore
Choose Backup settings, logos, logs ( not to local storage). This will create among other things a logs.zip file on the USB stick. Please post logs.zip here.

**Comment by Albarge** [comment]
Thanks for looking, much appreciated!

Not sure if relevant, but as I mentioned on the Victron forum, it turned out dbus-serialbattery was actually broken by VenusOS v3.30 also, I found reverting back to an older serialbattery worked. There was a mention of missing files in the install command window for the older version of serialbattery driver after it installed.

I'll just get the Package Manager logs now

**Comment by CaptainRivet** [comment]
Hi Kevin,
Had updated to 3.30 and with 7.7 setup helper and v10.15 was not working. Directly updating to 7.10 and v10.17 gui mods just now and still not working. Did manual update. There was no reboot after the install but I did one manually and no change…gui mods still not working. Have a cerbo GX.

**Comment by kwindrem** [comment]
CaptainRivet, I need lots more information that "not working". Any messages displayed on the GUI? What's shown for the three versions?

Also, logs would be very helpful. See instructions above.

**Comment by CaptainRivet** [comment]
No message shown. Screenshot of the p
ack manager with versions see blow.
![20240324_201703](https://github.com/kwindrem/GuiMods/assets/134114505/46ecd497-fd05-48ae-b957-ba56ce331607)
Gui mods simply not working, setting is on the bottom of the 
Page.
![20240324_201543](https://github.com/kwindrem/GuiMods/assets/134114505/b47afba6-2078-4ce6-9017-c89f3e04070c)
![20240324_201529](https://github.com/kwindrem/GuiMods/assets/134114505/6b741a86-929e-4bb9-83c1-62cfca4a8e34)
![20240324_201529](https://github.com/kwindrem/GuiMods/assets/134114505/ed03e327-772a-4e9c-a215-5257fc58d5ff)
Rebooted cerbo, no change. Venus V3.30 Large.

**Comment by CaptainRivet** [comment]
How can i re-install the V10.17 again?
There should be a automatic reboot after i installed 10.17 from V10.15? There wasn't.
Every update before it did but not this one.

**Comment by CaptainRivet** [comment]
Figured it out. 
Downgrading to V 10.16 gui mods and then upgrading to 10.17 didn’t work. Uninstalling gui mods and reinstalling 10.17 also didn’t work as gui mod is again not asking for gui restart during install.
What worked was uninstalling setup helper and gui mods and then install setup helper 7.10 via USB stick and then 10.17 gui mods, gui mods now working.
It seems you cannot go 7.7 to 7.10 setup helper and then install 10.17 gui mods, something is missing as gui mods is not asking for gui restart. From scratch works.

**Comment by kwindrem** [comment]
Sorry, can't help without logs.

**Comment by kwindrem** [comment]
You can always download again from the Package editor menu.

If you want a specific older version, set the branch/tag to that version then download it.

**Comment by CaptainRivet** [comment]
Kevin I figured out and gui mods working now. Described what I had to do in case someone has the same issue then I do.
