### ISSUE TITLE
Missing PV Inverter names

### ISSUE THREAD

**Issue by blieven1** [kwindrem/GuiMods#244]
Guimods 10.16

At the moment it displays -- instead of the name
![image](https://github.com/kwindrem/GuiMods/assets/12248588/08db9e75-8402-4eed-b7ab-4f19ab42f7d6)

They are named in the device list:
![image](https://github.com/kwindrem/GuiMods/assets/12248588/efc0fea7-e3d8-4e80-8e67-958c9e08d8e5)

The inverters are in fact the new Victron VM-3P75CT energy meters in PV role, connected via ve.can bus:
![image](https://github.com/kwindrem/GuiMods/assets/12248588/13686421-c894-4629-95d7-6f37c11a6188)

If I can help debugging let me know.

Kind regards,
Bjorn

**Comment by kwindrem** [comment]
This is likely because you are using an energy meter to supply the information for your PV inverters. a /CustomName parameter is needed in the dbus service for them. 

Can you send me screen shots one one of the devices in dbus-spy?

dbus-spy is a command line tool for inspecting dbus services.

**Comment by blieven1** [comment]
Sure, here you go: (it does seem to be filled in)

![image](https://github.com/kwindrem/GuiMods/assets/12248588/95c0d921-23cf-4195-a908-845650dfb24d)

**Comment by kwindrem** [comment]
Very interesting. I'm getting the name from the same dbus service as the power and as you show above the name is present.

Very odd in fact since I show a single dash "-" if the name field is not valid, not two dashes "--".

What version of firmware are you running so I can check the specific code for that version?

What does PV Inverter Details page show? (tap on the PV Inverter tile.)

In dbus-spy while showing the page you sent above type the 't' key to toggle between value and text attributes. If the name changes to '--' then I know what the issue is.

Thanks

**Comment by blieven1** [comment]
Hi,

I'm on v3.30

with 't' its indeed empty:
![image](https://github.com/kwindrem/GuiMods/assets/12248588/4170cb95-1158-488a-aa04-65181c3e2b43)

PV details is correct:
![image](https://github.com/kwindrem/GuiMods/assets/12248588/04b66ec4-2416-4653-942f-7f2357fb29b6)

**Comment by kwindrem** [comment]
I'll change my code to use .value instead of .text which is the difference between the overview and detail.

Thanks for reporting.

Are you using stock Victron drivers for the device or something a third party wrote?

If stock Victron I'll let them know there's a problem.

**Comment by kwindrem** [comment]
Just released v10.17. Please check ASAP as I have no way of testing here. Thanks.

**Comment by blieven1** [comment]
Yes,

Working now!

I used indeed all standard victron meters, no special drivers

Thanx for fixing!

Op 21 mrt 2024 om 20:39 heeft kwindrem ***@***.***> het volgende geschreven:

﻿

Just released v10.17. Please check ASAP as I have no way of testing here. Thanks.

**Comment by kwindrem** [comment]
Thanks. I reported to the Victron forum
