### ISSUE TITLE
Small error in ReadMe

### ISSUE THREAD

**Issue by CzarofAK** [kwindrem/GuiMods#25]
"Move the directory into it's active loca**it**on:
rm -rf /data/GuiMods
mv /data/GuiMods**2**-current /data/GuiMods"

should be:
"Move the directory into it's active _**location**_:
rm -rf /data/GuiMods
mv /data/**_GuiMods-current_** /data/GuiMods"

**Comment by kwindrem** [comment]
Thanks. I'll fix that in the next release.
