### ISSUE TITLE
Incomplete file set for v3.40~17

### ISSUE THREAD

**Issue by Roburetto** [kwindrem/GuiMods#250]
Incomplete file set for v3.40~17
![image](https://github.com/kwindrem/GuiMods/assets/22028625/da0f187f-c269-4f3d-97ef-4ad9997ba1f6)

**Comment by kwindrem** [comment]
Sorry. Been out of town.  I’ll get to it in the next couple of days

**Comment by kwindrem** [comment]
Should be fixed now.

**Comment by Roburetto** [comment]
Confirmed working. Thanks a lot for the update.
