### ISSUE TITLE
GUI mods screen flow view not working with version 10.41 on 3.33 and 3.40-26

### ISSUE THREAD

**Issue by neoneddy** [kwindrem/GuiMods#255]
GUI mods screen flow view not working with version 10.41 on 3.33 and 3.40-26

Had it accidentally set to auto install, stopped working an hour or two ago. 

I was able to roll back to version 2.88 Venus is and it worked there. I suspect something changed with the last update. Recently.

![image](https://github.com/kwindrem/GuiMods/assets/819083/eb8ba09f-8479-413e-a04e-16d221ff94b1)

**Comment by kwindrem** [comment]
Sorry about that. Somehow a typo got into the release that was not in my local folder. v10.42 should fix this.
