### ISSUE TITLE
Not all temperature sensors and solar charger shown

### ISSUE THREAD

**Issue by peterscarsten** [kwindrem/GuiMods#256]
Hello,
after updating to 10.42 this morning, I can't see all my solar chargers (I have twonin place) and all my temperature sensors in the overview.

I will add some screenshots. 

Best regards 
Carsten![Screenshot_20240616_100317_VRM.jpg](https://github.com/kwindrem/GuiMods/assets/113003596/e7f887a0-3b91-49b8-a456-df62f7a3d982)

![Screenshot_20240616_100339_VRM.jpg](https://github.com/kwindrem/GuiMods/assets/113003596/fe4d101a-ad13-4f74-9be5-7da207257178)

![Screenshot_20240616_100851_VRM.jpg](https://github.com/kwindrem/GuiMods/assets/113003596/787aee09-a069-4ccb-ae5c-557b5adbbeb6)

**Comment by TGTemplin** [comment]
I am having the same issue. My inverter temp will show, but none of my Ruuvitags. And I can only see the total solar. However, the hidden inverter is back.

**Comment by kwindrem** [comment]
GuiMods v10.43 should fix these problems

**Comment by peterscarsten** [comment]
Yes, it's fixed. Thank you
