### ISSUE TITLE
GuiMods v10.42 Ekrano GX Display Problem

### ISSUE THREAD

**Issue by roypsmith** [kwindrem/GuiMods#257]
After upgrading my Ekrano GX to GuiMods v10.42, the main page no longer displays my MP2. However, I also upgraded my Pi Venus OS and it displays my other MP2 correctly there.

RPSmith...

**Comment by kwindrem** [comment]
Not sure why this is happening but made a change and hopefully v10.43 will fix the problem.

**Comment by roypsmith** [comment]
Thanks!  I'll give it a try when it's available and get back to you.

**Comment by roypsmith** [comment]
Good Job!  All good now on v10.43

Thanks!  RPSmith...
