### ISSUE TITLE
Guimods White screen problem

### ISSUE THREAD

**Issue by Gexle** [kwindrem/GuiMods#261]
Hello Kevin

I updated to the latest Guimods version and now the display is white and I can't see anything anymore.

What should I do now??

How can I get it back??

![Weis](https://github.com/kwindrem/GuiMods/assets/123386828/1bfa9eb1-7c19-48dc-b472-b1f85e633465)

**Comment by kwindrem** [comment]
Reboot if you have not done so already.

Do you have ssh access? If so:

/data/GuiMods/setup uninstall auto

logs would also be very helpful.

tail -50 /data/log/PackageManager/current  | tai64nlocal
tail -50 /data/log/gui/current  | tai64nlocal
tail -50 /data/log/start_gui/current  | tai64nlocal



What firmware version?

**Comment by Gexle** [comment]
The Firmeware is V2.93 is run
restart didn't help!

**Comment by Gexle** [comment]
Where can I find the logs again?

**Comment by Gexle** [comment]
I can't find start_gui!

[logs.zip](https://github.com/user-attachments/files/16146136/logs.zip)

**Comment by kwindrem** [comment]
v10.54 is available now that should fix the white screen. Please set branch/tag back to latest if you changed it.

Thanks for reporting.

**Comment by Gexle** [comment]
Thank you, everything is working as before

Thank you
