### ISSUE TITLE
Battery Detail missing details.

### ISSUE THREAD

**Issue by angyp** [kwindrem/GuiMods#264]
Hi, I seem to be missing some details on my battery detail screen. Ie Consumed and  Remaining 

<img width="583" alt="image" src="https://github.com/user-attachments/assets/db0e7a7e-e1d6-4cdd-aff5-223d9e4d7944">

When I look at the BMS details I see the missing info.

<img width="582" alt="image" src="https://github.com/user-attachments/assets/55035788-6dfe-475c-9135-af236f1fda40">

Thanks

**Comment by kwindrem** [comment]
I only have a dumb battery so I a not debug this issue. I need to see the battery service in your system reported in dbus-spy which is a command-line utility

**Comment by kwindrem** [comment]
I just released some changes to the battery detail (GuiMods v10.60). Please check to see if you now see consumed and remaining values. Thanks

**Comment by chelle-hine** [comment]
I think this update has broken the display of Consumed (Ah) on the 'Battery detail' tab, when using a Smart Shunt. Today my Cerbo stopped showing Consumed (Ah) and instead shows an empty 'Aux Voltage' slot, even though I am using the Aux input on the shunt for Temperature. The 'Temperature' slot is displaying values correctly. I checked the package manager and my Cerbo has auto updated to V10.60, and was displaying fine before the update.

**Comment by angyp** [comment]
Works for me.

<img width="584" alt="image" src="https://github.com/user-attachments/assets/0f04d08c-2b70-4127-8bbc-9776887c4cb9">

**Comment by kwindrem** [comment]
I thing you should also be seeing remaining AH. Made another change (v10.61)

**Comment by chelle-hine** [comment]
@kwindrem v10.61 fixed my issue, thanks
![Battery consumed 2](https://github.com/user-attachments/assets/2e6ff01b-f6c8-4070-bade-ed4d71ebc44c)

**Comment by kwindrem** [comment]
There is still something wrong. The battery details page is showing both installed and remaining capacity so my details page should be including consumed and remaining. Remaining AH should appear next to Consumed AH.

**Comment by kwindrem** [comment]
chill-hine do you have a smart battery or a battery monitor/shunt? If shunt then that explains why there's no remaining value shown as installed capacity is not provided. let me know. thanks.

**Comment by chelle-hine** [comment]
> chill-hine do you have a smart battery or a battery monitor/shunt? If shunt then that explains why there's no remaining value shown as installed capacity is not provided. let me know. thanks.

I have a Smart Shunt and dumb batteries. I've also checked that when discharging 'Remaining time' shows OK. As you say, Shunts don't output the Remaining Ah, just time.

**Comment by kwindrem** [comment]
I'll close this for now then.

**Comment by angyp** [comment]
Something is still not right.

<img width="389" alt="image" src="https://github.com/user-attachments/assets/936de6b7-a757-49f5-9c16-11b6b064fc0c">


<img width="389" alt="image" src="https://github.com/user-attachments/assets/3e5be2ef-93e7-4348-9ca9-48bdc83062c4">

**Comment by kwindrem** [comment]
Made another fix v10.62

**Comment by angyp** [comment]
That works. Thanks

<img width="386" alt="image" src="https://github.com/user-attachments/assets/ec6c2285-4dfb-4f58-9e35-9c551560c38b">
<img width="383" alt="image" src="https://github.com/user-attachments/assets/a8cc3216-b561-4918-b4d4-50545c3f6e8a">
