### ISSUE TITLE
Little bit confused about supported Victron Versions?

### ISSUE THREAD

**Issue by ubarni** [kwindrem/GuiMods#268]
Hi,

my Cerbo GX has firmware 3.40 ~39 now.
The newest update shows version 3.50 ~13.

Is there a GuiMods release covering the new 3.50 versions?
The newest GuiMods release says: add support for v3.41

Thanks..
Uwe

**Comment by ubarni** [comment]
Well. 3.50 ~13 is a beta version. Are they also covered by GuiMods?

**Comment by kwindrem** [comment]
Yes v3.50 betas are supported
