### ISSUE TITLE
Observation - Solar Panel

### ISSUE THREAD

**Issue by Next9999** [kwindrem/GuiMods#27]
![AS](https://user-images.githubusercontent.com/54117519/144686481-aa023901-2a0b-4f82-9665-363e79a0d748.jpg)
I notice a small cosmetic... 

On the second screen of the Solar Panel.. The first Solar show Watt with digit

Again i loved the work you did AWESON

**Comment by kwindrem** [comment]
This is as designed. I display values up to 99.9 to 1/10 resolution, then switch to 1// resolution. This saves space for larger values.
