### ISSUE TITLE
Guimods V10.63 -> incomplete file set for V2.93

### ISSUE THREAD

**Issue by Gexle** [kwindrem/GuiMods#271]
Hello Kevin

Wanted to install the latest Guimods version V10.63....

But I get the message. ->  incomplete file set for V2.93

Thanks

**Comment by kwindrem** [comment]
Yup. Firmware versions prior to v3.10 are no longer supported.

There is an alternate branch/tag that will support older firmware but without any updates or bug fixes.

Set the branch/tag for all your packages to prevV3.10support.
