### ISSUE TITLE
Not working with VenusOS Beta 3.50-22

### ISSUE THREAD

**Issue by MBj1703** [kwindrem/GuiMods#273]
<img width="280" alt="Bildschirmfoto 2024-09-16 um 14 43 25" src="https://github.com/user-attachments/assets/90a56e6e-5c71-47b9-8f76-ded406962a4e">

**Comment by kwindrem** [comment]
Noted. Victron moved the location of the styles.css file so I need to figure out how to address that and still support older firmware versions. This may take some time.

**Comment by MBj1703** [comment]
Thank you!

**Comment by kwindrem** [comment]
Should be fixed now.
