### ISSUE TITLE
request : solar chgr tile : show output current/volts

### ISSUE THREAD

**Issue by gregsyoung** [kwindrem/GuiMods#276]
solar chgr tile shows PV details, but not “output” (volts/current)

details are available in cerbo by going into the solar charger in menu.. they are labelled “battery” (under the solar chatger details) 

when viewing the overview screen of all tiles with DC power flows from charger/inverter, solar chgr, battery and Dc loads (“DC system) 
.. this is the current flow that is missing from the view.

keep up the great work! 
and thanks for yr invaluable contribution to the communi

**Comment by kwindrem** [comment]
Yes, the battery current and voltage are missing from the PV Charger tile. It was a decision I made based on limited space.
