### ISSUE TITLE
the new firmware version V3.5-28  is not alowing the GuiMods to update  in active packages  says   ------ GuiMods  incomplate file set for v3.50~28 

### ISSUE THREAD

**Issue by deefpv1** [kwindrem/GuiMods#279]
the new firmware version V3.5-28  is not alowing the GuiMods to update 
in active packages  says   ------ GuiMods  incomplate file set for v3.50~28 

this hapend on the last update too as well 
hope can find a long term fix for this
![Screenshot 2024-10-03 at 17-06-03 Remote Console on LAN](https://github.com/user-attachments/assets/1e83f50e-af76-4112-a323-42c072ff4774)

**Comment by kwindrem** [comment]
As new firmware versions are released, there is a period of time where any modification will fail to work or install. This is especially true when running beta versions of the firmware. This is an ongoing issue and there is no "long term fix". Each time Victron updates a file GuiMods modifies, I must create a new modified file. 

In this case, a significant change to the generator logic was included as part of the beta release. It is going to take some time for me to redesign my modifications so that it is compatible.

I suggest you downgrade to the previous beta and disable automatic updates, or revert to the latest released firmware.

**Comment by donutFred** [comment]
Appreciate your work @kwindrem. This may not be the best forum to ask this, but I can't find an answer elsewhere on Victron professional... 

From GitHUb it looks like currently the latest firmware that you have released a modified file for is GuiMods [v10.67](https://github.com/kwindrem/GuiMods/releases/tag/v10.67) add support for v3.50~25

I'm currently running v3.50~20 on my raspberry Pi and the only online update I can see from the menu is v3.50~31

Is there a way to find Victron's v.30~25 update package anymore? Or, do I install v3.50~31 and live without GuiMods until you hopefully do a release (honestly, not really an option with the gastly non-dark mode!) 

I feel like I'm in an endless loop.... Victron keep releasing firmware updates that break GuiMods, so I revert back to v3.50~20, then Victron release another beta, meanwhile you release an update addressing the older firmware, which I cann't figure out how to downlaod anymore. So, I'm "stuck" on v3.50~20. Is there a better way?

**Comment by kwindrem** [comment]
Such is the cycle of beta testing. I have unfortunately not had the time to address the latest string of firmware updates so GuiMods won't work on them.

Unless you save the beta releases as they become available there is no way to go back to them. Only the latest beta is available.

The thing to do in this case is turn off automatic firmware updates so at least your system doesn't change firmware.

**Comment by kwindrem** [comment]
I have a version of GuiMods working for v3.50 and v3.51~2.

Let me know if you experience any issues.

Again note: GuiMods menu enhancements will not appear in the New UI (aka gui-v2).

You will however be able to configure the external transfer switch and link generator external run to manual run by switching back to Classic UI.

This also applies to Package Manager. If you configure Package Manager for auto downloads and installs then these will occur in the background even though you won't have those menus.
