### ISSUE TITLE
GuiMods Cant Install on Cerbo GX Firmware 3.51

### ISSUE THREAD

**Issue by robertvygo** [kwindrem/GuiMods#284]
Getting the file set is missing message...

**Comment by kocki2** [comment]
same to me ...
![g01](https://github.com/user-attachments/assets/36cf2aff-b07f-4c43-9f92-12768ef20c6a)

**Comment by kwindrem** [comment]
fixed in GuiMods v10.75

**Comment by ewinkley** [comment]
I appreciate your work, @kwindrem.  It adds so much value to the Cerbo system.

I don't see 10.75 is available/published yet - will it be available soon?  Can you advise how I one can donate to you to show our appreciation?

**Comment by kwindrem** [comment]
Sorry, thought I'd done that. Should be there now
