### ISSUE TITLE
Not a issue only a question ;-)

### ISSUE THREAD

**Issue by testpaul999** [kwindrem/GuiMods#285]
Hi, 
Is it possible Show the new gui-v2 at the RPI display?
Regards

**Comment by kwindrem** [comment]
GuiMods would not be able to provide that path to gui-v2 on the PI platform. Please see recent posts on the Victron community forum on the subject.

Victron is working on this but there are issues with the OS kernel that needs attention first.

**Comment by testpaul999** [comment]
👍🏻 thx
