### ISSUE TITLE
GuiMods 10.78 - Incomplete file set for v30.6~7

### ISSUE THREAD

**Issue by aph70** [kwindrem/GuiMods#287]
Unable to unstall guimods on the the above named version.

**Comment by kwindrem** [comment]
Noted. I'll need to update it for this version. Victron made a change in naming of the generator component and SetupHelper is not designed to handle this so it may be some time before I can figure out a way to deal with such changes.

**Comment by kwindrem** [comment]
GuiMods has been updated to support v3.52~3 and v3.60~13
