### ISSUE TITLE
PV charger tile shows the same voltage for all chargers 

### ISSUE THREAD

**Issue by t440142** [kwindrem/GuiMods#44]
Hi,

the voltages for each charger are displayed correctly on the detailed image below.
It looks like only the first variable is taken for all entries.

Can you have a look at this.
Thanks

Best regards
Peter

Firmware
PV Charger: 1.59
Cerbo GX: 2.84
SetupHelper: 4.7
GuiMods: 5.16

**Comment by kwindrem** [comment]
Should be fixed in v5.17

**Comment by t440142** [comment]
Thank you.
