### ISSUE TITLE
digital inputs

### ISSUE THREAD

**Issue by andrewcrosse** [kwindrem/GuiMods#52]
hi is there anyway to get digital inputs to show state?

**Comment by kwindrem** [comment]
Any digital input that is configured to a specific function will show in the device list. The state of that input will then be the first parameter shown for the device.

If you are asking if GuiMods could show digital input states, then yes it would be possible to build another overview to show digital input states, but I have no plans to do so.

**Comment by andrewcrosse** [comment]
okay thanks anyway, thanks for work on guimods
