### ISSUE TITLE
PV Voltage and PV Current are missing on OverviewMobileEnhanced.qml page

### ISSUE THREAD

**Issue by gharshaw** [kwindrem/GuiMods#58]
@kwindrem 
I looked at the code in OverviewMobileEnhanced.qml. It appears that for Current, the code is calling for an invalid dbus item 
"VBusItem { id: pvCurrent; bind: Utils.path(pvChargerPrefix, "/Pv/I") }" At least I don't have that value on my DBUS for my SmartSolar Charger.
I  believe we need to calculate for the current by dividing "/Yield/Power" by "/Pv/V" . Does this sound correct?
![image](https://user-images.githubusercontent.com/79295813/167707982-63fe9ff2-efec-4451-835c-fd51ee7f0391.png)

Regards,
Gene

**Comment by kwindrem** [comment]
You are correct. Victron dropped the current parameters a while back and I thought I'd made these changes but missed this one. I'll get on it.

**Comment by kwindrem** [comment]
fixed in v5.26

**Comment by gharshaw** [comment]
That was fast.
Thank you
