### ISSUE TITLE
Temperature-Tiles on Main-/Flow-Screen are empty

### ISSUE THREAD

**Issue by LaPimienta** [kwindrem/GuiMods#64]
Values of Ruuvi tags are shown in e.g. Tank/Temp/Input screen but not in the tiles on the flow screen. This happened after an update to Guimods 6.3 on firmware 2,87. Decided to make a complete fresh install with firmware 2.89 and Setuphelper etc but without success. I mentioned that after a reboot for a very short time the temp-tiles on main screen are filled maybe if not all of my 6 Ruuvis are initiated. 
![Main-Screen](https://user-images.githubusercontent.com/111305237/185740781-2e070012-ac76-4a23-8486-6e320eef7192.png)
![Overview-Screen](https://user-images.githubusercontent.com/111305237/185740797-d24c9f64-e2ba-46a3-9c4a-db6325542a37.png)
![Firmware-2 89](https://user-images.githubusercontent.com/111305237/185740819-d29db11a-2320-4cf5-b3a9-a3acf3658905.png)
![GUIMODS-Packages](https://user-images.githubusercontent.com/111305237/185740824-f2efe025-bb65-49a7-9b43-77af075af41b.png)
![GUIMODS-Settings](https://user-images.githubusercontent.com/111305237/185740827-4c030700-c372-4dfa-a3ec-77e78d5999a9.png)

**Comment by kwindrem** [comment]
fixed in v6.4
