### ISSUE TITLE
Propane on Overview (How to)

### ISSUE THREAD

**Issue by Next9999** [kwindrem/GuiMods#67]
How to remove the propane tank on the first pas?

![image](https://user-images.githubusercontent.com/54117519/190853185-7888944c-0ff5-46cb-bbe1-8cb008c07198.png)

**Comment by kwindrem** [comment]
There's an option in Device List / Settings / Display & Language / GuiMods to show or hide tanks on the overview page.

**Comment by Next9999** [comment]
Perfect Tks... great work.. Your display is way better than the Victron standard
