### ISSUE TITLE
Watts vs KW precision on grid/load panels

### ISSUE THREAD

**Issue by GeoZBee** [kwindrem/GuiMods#69]
Just installed v6.9 and so far it’s great! Many of the new features and enhancements are well positioned and functional. I’ve also noticed improved stability as well!

Currently, in the AC Grid and load panels in the flow screen, any time watts exceeds 999 the precision automatically changes to KW. While I’m sure that’s quite handy for larger systems where KW precision is appropriate, I find it less precise in my smaller (<5000w) installation —where every watt counts. 

I would like to suggest that those values retain their 4 digit precision (since it will visually consume about the same footprint, eg 1.50 KW vs 1500 W) until 9999, or perhaps an option to choose W vs KW?

Thanks again for the work you’ve put into this mod. This remains, by far, on of the best mods I’ve implemented for my Victron system.

**Comment by kwindrem** [comment]
Added a threshold (1000 - 10000) for the transition between units and K-units.
