### ISSUE TITLE
Guimods white screen

### ISSUE THREAD

**Issue by RobDuthie** [kwindrem/GuiMods#74]
White screen after Vensus update to version 2.89, Control works OK still,  Uninstall Guimods and all is OK again.
New version not compatble with the new Vensus update.
I have noticed this a few times now when having guimod installed when the venus does an update  you always get a blank screen white, and you can't update the vensus software any more re image SD and start again seems to be the only fix?
[
[current.txt](https://github.com/kwindrem/GuiMods/files/9720155/current.txt)

**Comment by stsmedia** [comment]
Same issue here. How do I uninstall guimods via ssh console?

**Comment by neoneddy** [comment]
Wanted to report same.  I knew what I signed up for so I'm re-imaging the SD card now.

**Comment by kwindrem** [comment]
Tapping the inverter tile to bring up the details page works on my test system (RPI4).

**Comment by RobDuthie** [comment]
Hi
All good now with version 6.15. I like the tank bar format mods in the Guimods nice touch.
