### ISSUE TITLE
V6.11 No longer showing PV Charger information

### ISSUE THREAD

**Issue by gainestr** [kwindrem/GuiMods#75]
Newest version is no longer showing PV charger information.  Just installed and can not see my PV status even though it is night and there is no output from the solar array.  Maybe this is something new when a device reads zero output and it will show up in the morning but for now I went back to v6.10.  Pictures below are showing Dashboard from v6.10 with the PV status and v6.11 without any status and a blank space instead.
I am using DC Coupled overview.  Also, it appears that the battery Watt/Kilowatt threshold isn't working properly(Battery should be showing Watts if the threshold is set at 1000).  As seen below, it is showing -0.09KW instead of -95.4 Watts.  Also, it is misspelled as Watt/Kilowat in the settings.

<img width="480" alt="Screen Shot 2022-10-05 at 10 11 05 PM" src="https://user-images.githubusercontent.com/33384039/194206148-e7cc4abc-0c65-49ce-8e60-57d04509a2af.png">
<img width="482" alt="Screen Shot 2022-10-05 at 10 12 04 PM" src="https://user-images.githubusercontent.com/33384039/194206152-6d6758ef-f9ef-49ea-bdaa-5151fd671456.png">

**Comment by kwindrem** [comment]
Fixed now in v6.12.

**Comment by gainestr** [comment]
Confirmed, DC Coupled overview is now displaying PV charger.  I edited and added a couple more observations/issues above.  Looking good!  Love the new Watt/Kilowatt option.  Thank you.

**Comment by kwindrem** [comment]
New issues fixed in v6.13
