### ISSUE TITLE
tank % and volume  dont fit in space, some rearrangement?

### ISSUE THREAD

**Issue by virtuvas** [kwindrem/GuiMods#76]
as per the title,

![image](https://user-images.githubusercontent.com/17377407/194234289-9bcefe3f-b67a-458f-9b45-eacecd9a98ff.png)

remote console messes up values' presentation, maybe giving them a bit more space against the empty space for the text string to the left of each cell? 
tbh don't remember how it looks in real screen, it may actually be ok locally (will have to test on next visit to the boat)  which makes it even more confusing.

2.91, guimods 6.11

cheers

V.

**Comment by kwindrem** [comment]
v6.15 now allows you to select %, units or both in the bars. I've also allotted more width to the bar where it is available.

Let me know what you think.

**Comment by virtuvas** [comment]
![image](https://user-images.githubusercontent.com/17377407/194475906-dbf58150-bccc-4d5b-bb0b-57b3118c1989.png)

perfect!

thanks Kevin!

V.
