### ISSUE TITLE
v6.17 

### ISSUE THREAD

**Issue by dmsims** [kwindrem/GuiMods#80]
Upgrading to v6.17 of Guimods on a Pi3B running Venus 3.00~4

Message is "GuiMods file set incomplete"

Tried removing and reinstalling - same message

Only other package installed is Setuphelper

**Comment by kwindrem** [comment]
v3.00~4 just released and I have been away. Will get to the incompatibility issue right away.

**Comment by kwindrem** [comment]
v6.19 is available now that adds support for v3.00~4
