### ISSUE TITLE
Change input AC1 from 'grid' to 'generator' when generator running

### ISSUE THREAD

**Issue by gr0mit1** [kwindrem/GuiMods#89]
Hi Kevin
Following on from my post on one of the Victron forums I've done a bit more investigation as to what I think I need.
If i manually start the generator, I want the AC1 input to think it;s a generator, rather than the grid.

From the shell I can execute the following command:
dbus -y com.victronenergy.settings /Settings/SystemSetup/AcInput1 SetValue 2

which tells the Cerbo to think the input is a genny.  Can you execute this command when I 'Start' the generator from the generator panel?

And when I stop the generator, execute the following command:
dbus -y com.victronenergy.settings /Settings/SystemSetup/AcInput1 SetValue 1

to revert to 'grid' operation.

I am not (yet!) familiar with the code, but a quick hunt makes me think I just need to execute these at some appropriate point in either /opt/victronenergy/dbus-generator-starter/startstop.py or  /opt/victronenergy/dbus-generator-starter/dbus_generator.py but I can't fathom how it works.

Any tips on how to achieve this please?

Cheers
Tim

**Comment by kwindrem** [comment]
What you suggested would work to a point. The dbus calls take around 1 second each so it's not something that can be included in other code very easily. Plus you aren't changing the input current limit which will also be different between grid and generator.

I have created a new package ExtTransferSwitch which I believe does the complete job. It's still somewhat of a hack but it seems to work. It uses a digital input to switch between grid and generator configurations. You can wire this to your transfer switch or to a manual switch, or possibly to the generator run/stop relay output.

**Comment by gr0mit1** [comment]
Hi Kevin

Thanks for this.  I've installed it and a brief test confirms it rocks!!! This is EXACTLY what I was trying to achieve, and you've done it in a much more elegant way.  Especially limiting the generator current and grid current seperately.

I think I'll use a relay or optocoupler to operate the input signal which I will feed from a PSU on the genny output, so if the genny is producing volts the relay/opto will operate and switch to generator mode.  Need to rummage through my junk box for a suitable relay or optoisolator now!

Thanks so much for this - it looks perfect.  I'll let you know how I get on.


Greetings from UK
Best regards
Tim Robinson

________________________________

**Comment by kwindrem** [comment]
Glad it fit your needs. Many on the Victron forum have asked for something similar.

Deriving on grid/on generator from the generator producing power probably isn't the best unless that also switches your transfer switch to the generator. You might look into grid power signal detection (a simple relay on the grid side) might be a better source to switch the transfer switch to the generator side and signal the GX device.

I am considering an enhancement that would prevent the generator from starting if the transfer switch was on grid. If I do that and you use the generator running to signal "on generator" then the generator might not ever start.

What I'm thinking is changing the state of Do not run generator when AC is in use like I'm doing for other parameters. It would be in the state selected by the user when on grid and turned off when on generator. That way the generator would not urn unless the transfer switch was on generator.

Comments?

**Comment by houlster** [comment]
How do you install this?  It says ot use SetupHelper to install, which I have, but this doesn't show up in the 'Inactive packages' for install.

**Comment by kwindrem** [comment]
You may need to add it manually.
Select 'new' then add in the package name: ExtTransferSwitch, user: kwindrem, branch: latest
