### ISSUE TITLE
Small suggestion - why not move DC to the right?

### ISSUE THREAD

**Issue by svalbard2** [kwindrem/GuiMods#92]
Hi, I only have DC Loads so I renamed DC System to DC Loads. For input I have the Shore, Generator and an Alternator. 

![DC Loads and Alternator](https://user-images.githubusercontent.com/119114646/204093828-c5886bf2-337d-45a4-9ad9-f5c60899d5a1.jpg)

Is it possible to move the DC Systems, or on my screen DC Loads, to the right of the battery? Under AC Loads?

**Comment by kwindrem** [comment]
I will look into moving DC System to the right hand column.

While it would technically be possible to dynamically move tiles around (or based on user preferences), it adds a significant amount of complexity to an already complicated layout.

**Comment by rspott** [comment]
> ![DC Loads and Alternator](https://user-images.githubusercontent.com/119114646/204093828-c5886bf2-337d-45a4-9ad9-f5c60899d5a1.jpg)

@svalbard2 
Is this picture simply a mockup or do you have this working now?

**Comment by kwindrem** [comment]
I have swapped PV Charger and DC System tiles on the DC and AC coupled flow overviews. This is currently in beta test along with other enhancements/changes.

If you would like to test this, go to Settings / Package manager / Active packages and tap on GuiMods. Change the branch/tag to "beta". Don't forget to change this back to "latest".

svalbard2, yes this is implemented and has been for some time. Go to Settings / Display & language / GuiMods and select GuiMods DC Coupled under Flow overview. There's also a GuiMods AC Coupled page for those with PV inverters and/or loads on AC input.

**Comment by kwindrem** [comment]
done
