### ISSUE TITLE
AC Tile not showing on flow screen

### ISSUE THREAD

**Issue by nickmoody** [kwindrem/GuiMods#94]
The AC Tile is no longer displayed on the flow screen. The Phoenix Inverter is connected and the switch still works (on / off / eco). Tried rebooting the Cerbo. VRM still shows the Inverter and AC loads as does the mobile app. If I switch to Victron stock flow then the AC tile shows.

**Comment by kwindrem** [comment]
Should be fixed now (v7.7)

**Comment by nickmoody** [comment]
It’s fixed :-) that was fast! Thanks for all your work on this project, it’s very much appreciated. Cheers.

![9E7CC3B0-7EA2-495A-83C9-9A10CECD1743](https://user-images.githubusercontent.com/20305226/208194124-ba3714cc-1a99-4d18-993c-41b84b2a06d5.png)
