### ISSUE TITLE
Flow overview modification - GuiMods DC Coupled

### ISSUE THREAD

**Issue by jrolleyecora** [kwindrem/GuiMods#97]
Hi,
First of all, congratulations for the great job you are doing.
Would it be possible to make such a change? It would be something similar to GuiMods DC Coupled but without the Wind Generation and Fuel Cell box. What modifications should I make? What files should I modify? I would also like to see the temperature of the battery as can be seen in the image

![Captura](https://user-images.githubusercontent.com/17767146/209400277-b8b926b4-467d-430b-b71d-eef35cba0d91.JPG)

**Comment by kwindrem** [comment]
That page is in the file OverviewFlowComplex.qml. You can delete the items you don't want and expand the size of the tiles you want bigger.

Your AC Loads tile is similar to what I provide in the GuiMods Simple page so you could lift that from Overview HubEnhanced.qml.

Temperatures are displayed as mini-tiles along the bottom if they are included in the dBus system. Adding temperature to the battery tile would be easy but you need to remove something else.

**Comment by jrolleyecora** [comment]
Thanks, I'll try it...
